### ISSUE TITLE
Frak Fahrzeuge Abschleppen

### ISSUE THREAD

**Issue by iHostiiX** [TerraTex-Community/TerraTex-Reallife-Reloaded#101]
PD kann Frakfahrzeuge abschleppen. Diese bleiben solange Verschlossen bis ein Leader / Coleader sie für einen höheren Betrag auslöst.

Regeln müssen natürlich geändert werden. z.b. kein Abschleppen beim Gangfight o.Ä

**Comment by geramy92** [comment]
Hinfällig, da wir ein neues Fraktionsfahrzeugsystem planen
