### ISSUE TITLE
Abschleppen von Motorrädern

### ISSUE THREAD

**Issue by iHostiiX** [TerraTex-Community/TerraTex-Reallife-Reloaded#102]
Wir sehen oft das Motorräder irgendwo offline am job stehen, jedoch können wir als PDler nichts machen. Ich könnte mir vorstellen das diese Motorräder irgendwie auf einen LKW geladen werden, es gibt ja einen mit ladefläche und man diese dann wie normale Autos im PD abschleppen kann.

**Comment by scriptcodeDE** [comment]
Work in Progress
