### ISSUE TITLE
/pcolor Vorschau

### ISSUE THREAD

**Issue by iHostiiX** [TerraTex-Community/TerraTex-Reallife-Reloaded#108]
Eine Vorschau Funktion für /pcolor wäre Toll, so kann man sich das Fahrzeug in der gewählten Farbe mal schauen und eventuell nochmal ändern oder eben so lassen.

**Comment by geramy92** [comment]
eigentlich haben wir deswegen die Textfarbe.... aber ich hätte vllt. eine weitere idee die gehen würde müssen wir mal schauen

**Comment by scriptcodeDE** [comment]
Work in Progress

**Comment by scriptcodeDE** [comment]
Should be closed
