### ISSUE TITLE
Verlust vom Skill-Booster nach Nickchange

### ISSUE THREAD

**Issue by ShibaSativa** [TerraTex-Community/TerraTex-Reallife-Reloaded#109]
Dieser Bug ist mir leider erst ziemlich spät aufgefallen, aber sobald man einen Nickchange vollzogen hat, verliert man seinen Skill-Booster. Ich habe meinen vor etwa 2-3 Wochen gekauft und er ist verschwunden. Ich erhalte meine Aufträge nicht mehr doppelt gezählt

**Comment by geramy92** [comment]
Alle haben ihre Sachen zurück. Bug ist behoben.

**Comment by ShibaSativa** [comment]
Wurde der Bug jetzt schon behoben oder passiert das beim nächsten Update? Ich bin nämlich immer noch nicht im Besitzt des Skill-Boosters...

**Comment by geramy92** [comment]
du hast in der DB deinen Skill Booster. Da dies ein Timestamp ist, kann es jedoch sein, dass die 30 Tage wohl schon um sind.

**Comment by ShibaSativa** [comment]
Aber ich habe ja keine 30 Tage meinen Skill-Booster aktiviert. Heißt das ich habe für 30 Tage bezahlt, bekomme aber nach 3 Wochen den abgenommen?

**Comment by geramy92** [comment]
Zum ersten lies bitte meinen Satz erneut und verstehe was dort steht. Zum anderen ist das hier nicht der Supportbereich für irgendein Server sondern ein Bereich zum Melden von Fehlern für das Script!
