### ISSUE TITLE
Prestige kaufen und Upgraden

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#11]
Der Preis für einen kauf oder Upgrade vom Prestige sollte vom Bankkonto bezahlt werden. (Derzeit vom Bargeld)

**Comment by geramy92** [comment]
/upgradeprestige wird bereits von der Bank bezahlt....
Prestige_load.lua L80
`changePlayerBank(thePlayer, -preis, "sonstiges", "Prestigeupgrade")`

**Comment by geramy92** [comment]
Verkauf geht absofort auch auf Bank zurück

**Comment by geramy92** [comment]
gefixt für /buyprestige
