### ISSUE TITLE
Intern für MTA-Idee

### ISSUE THREAD

**Issue by DominicaliasBroS** [TerraTex-Community/TerraTex-Reallife-Reloaded#111]
Wie wäre es mit einem Befehl wzb. /fmanage oder /finfo.
Mit diesem öffnet sich dann ein Fenster, bei dem man als Co/Leader Zugriff darauf hat es zu bearbeiten. 
Als Mitglied sprich Rang 1-4 können jediglich den Text des Fensters sehen. Das wäre gut für Besprechungstermine und nebensächliche Termine.

**Comment by geramy92** [comment]
Da dies jetzt über das Forum auf dem TT Server abgedeckt wird, nicht mehr nötig.
