### ISSUE TITLE
Mehr Truckerjob-Orte

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#121]
Hey.
Ich würde es cool finden, wenn neue Truckerjob Orte hinzugefügt werden könnten.
Der Truckerjob ist nach einer Zeit richtig einseitig, man hat immer die gleichen Orte..
Eine Idee wäre, alle Tankstellen (z.B.) als Ort zu markieren. Momentan ist ja nur die eine am Burgershot Nord. Natürlich könnte man ja auch noch z.B. mehrere 24/7 markieren. 
Wenn das dir zu viel Arbeit wäre, dann könnte ich auch die Koordinaten markieren gehen und dir zuschicken.

Liebe Grüße;

**Comment by geramy92** [comment]
#121 #122 #123
