### ISSUE TITLE
Änderung Fahrzeugsystem - Spawnes & Saves

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#125]
Zwar gibt es /park und /towveh um Fahrzeuge zu respawnen aber zukünftig sollte es so sein, dass bei einem Server neustart Schaden und Ort des Fahrzeugs gespeichert werden und das Fahrzeug auch dort wieder spawned. 

/towveh sollte auch Geld kosten.

**Comment by DarkCitizen** [comment]
Soweit ich weiß kostet /towveh doch schon Geld
