### ISSUE TITLE
24/7 Item Beschreibungen

### ISSUE THREAD

**Issue by Vanity1206** [TerraTex-Community/TerraTex-Reallife-Reloaded#127]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Geh in den 24/7 Shop. Wenn man alle Item Beschreibungen liest fällt einem auf das ab dem "Carfinder" die Beschreibungen nicht mehr passen.

**Comment by StalkerGER** [comment]
Ab da werden auch die Geldbeträge falsch angezeigt, weil die Rubbellose fehlen.
