### ISSUE TITLE
Neue Truckerjob-Orte funktionieren nicht

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#128]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #121 

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Neue Orte des Truckerjobs werden nicht angezeigt.

**Comment by geramy92** [comment]
Ist bereits gefixxt und mit dem nächsten GMX drauf siehe https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/commit/339c00856476d70051201f644ca97bd8fa22f500
