### ISSUE TITLE
Idee - Fraktionswagenmissbrauch - Jobben

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#13]
Überprüfen ob es einfach möglich ist

- Wenn jemand mit einem Frakwagen gefahren ist und dann einen Job ausführt, während der Frak wagen nur x Meter entfernt ist, ob dann automatisch eine Strafe kommt oder Frakwagen teuer respawned.

**Comment by geramy92** [comment]
Ich glaube, dass würde eines der beiden Probleme mit sich bringen:

1. Entweder wir haben einen kleinen Radius: dann wären manche Parkplätze außer Reichweite oder sie würden weiter außerhalb parken
2. Oder Radius ist so groß, dass wir ggf. Gefahr laufen andere Sachen zu beeinflussen (müsste geprüft werden). (Beispiel: Person xyz fährt nur mit da 3 andere Gangfight machen und geht dann aber Jobben)
Die Frage wäre auch: gibt es eine Zeitliche Komponente?

Mir fällt gerade keine andere Lösung ein wie man das prüfen sollte sinnvoll, dass man das System auch nicht austricksen kann. Allerdings wäre ein erster Schritt, bei /getjob zu prüfen ob derjenige duty ist oder nicht. Und wenn jemand duty ist, ein Job beginn gar nicht erst zuzulassen. Problem wären lediglich Fraktionen ohne Duty (News, böse Fraktionen, NAME)

**Comment by Maxx4u** [comment]
Zu 1. Stimmt. So nicht lösbar. Möglichkeit wäre nur mittels einer "Zone" die unsichtbar ist. Aber auch das würde mit Punkt 2 konfrontieren.

2. Das würde garantiert passieren. Also auch nicht akzeptabel.

Das Problem betraf zu damaliger Zeit leider genau die "bösen" Fraktionen. (Nicht nur, aber am häufigsten)
