### ISSUE TITLE
Ton bei neuem Taxi-Ruf

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#131]
Sofern ein Taxi gerufen wird, wäre es für alle Taxi-Fahrer nett, wenn die Taxi-Fahrer im Dienst einen Ton abgespielt bekommen würden.

**Comment by BritishEye** [comment]
#129 
Muss nur noch angenommen werden. Für die Medics sollte es eigentlich gleich gehen. Muss man nur die entsprechende Datei finden.

**Comment by scriptcodeDE** [comment]
Du weisst schon, dass dein Code nicht funktionieren wird?

Sounds können nur über Client-Scripte abgespielt werden. mobile_old scheint sehr stark ein Server Seitiges Script zu sein.

**Comment by BritishEye** [comment]
Oops, stimmt. Ja, ich bin auch nicht perfekt. ^^

**Comment by geramy92** [comment]
siehe @scriptcodeDE  ansonsten fehlt die möglichkeit das auch abschalten zu können,m denn ich denke das wird einige Taxifahrer nerven

zudem sich die Frage stellt: ob es wirklich so sinnvoll ist oder ob man nicht einfach zum outputChatBox einfach ein showError(playerElement, Message) hinzufügt. Diese haben einen Ton (sofern aktiviert) und erscheinen oben losgelöst in einem extra UI

**Comment by scriptcodeDE** [comment]
Die Lösung mit dem Aufruf der showError-Funktion finde ich echt gut. Ich bau das gleich mal ein.
