### ISSUE TITLE
Umgekehrte Aufträge beim Truckerjob

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#133]
(Sprich: Hol die Ware und bring sie zum Hafen)

Besonders interessant bei den Aufträgen mit Trucks und Anhängern. Würde noch mehr Abwechslung reinbringen.

**Comment by BritishEye** [comment]
Warum? Ist doch streng genommen das selbe.
Du fährst beim Truckerjob los, Holst die Ware ab und bringst sie zurück.
Das gleiche als wenn man das so lassen würde, wie es momentan ist.
Du holst die Ware beim Truckerjob, bringst sie zum Marker und fährst wieder zurück.
Beides hat den selben Weg. (Truckerjob -> Marker -> Truckerjob)
Also viel Abwechslung ist da nicht drinn, eventuell etwas mehr Reallife/Roleplay.

**Comment by geramy92** [comment]
ganz ehrlich: Zu viel Aufwand für zu wenig nutzen

**Comment by scriptcodeDE** [comment]
Ich kann dir das gerne scripten :D
