### ISSUE TITLE
Biz - Kasse

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#14]
- Bizkasse aus entfernung abfragen
- Bizkasse auf Bankkonto überweisen lassen

**Comment by geramy92** [comment]
Generell halte ich das eher für eine unrealistische Lösung. Wie wäre es stattdessen mit einer Bizmanger App oder ähnliches für den TerraLappTapp? Könnte man ggf. ja auch mit anderen Sachen kombinieren (neue Bizfeatures oder als neues Feature für die Banking App)

**Comment by Maxx4u** [comment]
Fällt somit mit der App für Prestige zusammen?!

**Comment by geramy92** [comment]
See new Ticket #23
