### ISSUE TITLE
Bankkonto für Ehepaare

### ISSUE THREAD

**Issue by DaBunka** [TerraTex-Community/TerraTex-Reallife-Reloaded#142]
User die INGAME verheiratet sind, sollten die Möglichkeit haben ein gemeinsames Bankkonto (Sparbuch) zu eröffnen.
Sodass beide User jederzeit Zugriff auf das gemeinsame Sparbuch haben.

**Comment by geramy92** [comment]
Das würde zu neuen Problemen führen: Scheidungen, Ausnutzen, etc.
