### ISSUE TITLE
Premiumfahrzeuge zu teuer

### ISSUE THREAD

**Issue by BOBAtm** [TerraTex-Community/TerraTex-Reallife-Reloaded#146]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [ ] Feature Request / Enhancement
- [X] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Premiumfahrzeuge sind zu teuer:
Stallion: 420 K $ => 50-100 K $
Hotknife: 470 K $ => 200-300 K $
Mower: 6,5 K $ => 1-2 K $
Camper: 58 K $ => 10-20 K $
Journey: 650 K $ => 50-100 K $
Vortex: -
Oceanic: 57 K $ => 20-30 K $
Pony: 51 K $ => 5-10 K $
Hermes: -
Stretch: 2,5 KK $ => 200-300 K $
Stuntplane: -
Mesa: 67 K $ => 20-30 K $
Rancher: 96 K $ => 10-20 K $
Sandking: 1,3 KK $ => 200-300 K $
Club: 53 K $ => 5-15 K $
Flash: 35 K $ => 5-15 K $
Huntley: 360 K $ => 50-100 K $

Bitte ändern.

**Comment by StalkerGER** [comment]
Was soll daran denn noch Premium sein, wenn man die günstig wie jedes andere Fahrzeug kaufen kann?
Da hab ich ja direkt keine Lust mehr auf so ein Fahrzeug zu sparen...
