### ISSUE TITLE
Fahrzeuginfo

### ISSUE THREAD

**Issue by leoncon99** [TerraTex-Community/TerraTex-Reallife-Reloaded#149]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Man sollte wenn man ein Fahrzeug kauft so eine art steckbrief im kaufmenü haben. z.B. Stärken, Schwächen und Top Speed.

**Comment by geramy92** [comment]
gidf.de

ich glaube kaum das sich irgendwer bei einem solchbekannten Spiel die Mühe machen will eine solche liste auch noch ingame einzubauen wenn sie schon gefühlte 10 mio mal im netz existiert
