### ISSUE TITLE
Nach kick vom AFK-System alle Waffen weg

### ISSUE THREAD

**Issue by leoncon99** [TerraTex-Community/TerraTex-Reallife-Reloaded#153]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Kauf eine oder mehrere Waffen
2. Lass dich vom AFK-System kicken
3. Connecte neu
4. Waffen sind nicht mehr da

**Comment by geramy92** [comment]
Das ist kein Bug

Es ist Absicht, dass kick = alles weg
