### ISSUE TITLE
[Diskussion] Macht ein Slack für alle Entwickler/Helfer sinn?

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#156]
Slack: https://slack.com/is 

ist eine kostenfreie (in Standardversion) Chat Software, die für Entwickler ausgelegt ist. Über diese können einfach Snippets, Code, Datein getauscht werden. Zusätzlich bietet diese Software (Erhältlich als App, Desktop App und Browser App) die Möglichkeit ans Github und Jenkins angebunden zu werden (Push und Info Nachrichten).

Vorteile wären hier:
- Entwickler und Helfer von TT haben eine gemeinsame Plattform zu diskutieren und sich auszutauschen
- Aktuellere Infos
- Möglichkeit einfacher zusammenzuarbeiten oder um Hilfe zu fragen beim Scripten für TT

Nachteil:
- man kann nur durch invite rein (jeder der drin ist kann inviten)

Was haltet ihr davon? 
@xerox8521 @BritishEye @scriptcodeDE @Maxx4u @Wer_sonst_noch_interesse_haben_könnte...

**Comment by scriptcodeDE** [comment]
Find ich gut 👍

**Comment by xerox8521** [comment]
Sieht gut aus.

**Comment by geramy92** [comment]
Da Slack mit Guestaccounts nur ab einer teuren kostenpflichtigen Version möglich ist, habe ich beschlossen stattdessen gitter.im zu nutzen. Hat zwar weniger funktionen aber für eine einfache Entwickler Umgebung reicht es aus. Einfach auf den gitter-chat button im Repo (Readme.md) klicken :)
