### ISSUE TITLE
Fahrzeuge von Usern die offline sind, können nicht beschädigt werden

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#158]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [x] Question

Aufgrund der vermehrten Übergriffe auf Fahrzeuge von Usern die offline sind, währe es evtl vom Vorteil (soweit gewollt) wenn die Fahrzeuge von Usern die offline sind, entweder nicht beschädigt werden können oder die Reparatur dann kostenlos ist.

Sofern nicht gewollt, eine Regelung was man mit Usern macht die so etwas praktizieren, ob dieses vom PD verfolgt, oder da administrativ gegen vorgegangen werden soll.

**Comment by geramy92** [comment]
Das ist bereits so.
Ausnahme sind nur Reifen und äußerliche Schäden.

**Comment by StalkerGER** [comment]
"Ich geh mal offline, mach mal Schaden an meinem Fahrzeug damit es wieder ganz ist"

Abfrage ob das Fahrzeug bereits Schäden hat, wenn ja wird der Betrag gesichert, und weitere Schäden werden nicht dazu gerechnet, solange User offline. (falls so überhaupt möglich).
Wenn User dann connectet, muss er die vorher vorhandenen Schäden bezahlen.

Evtl bekommt man dann die User weiterhin dazu, ihre Fahrzeuge repariert, und evtl aufgetankt, bei ihren Häusern/Parkplätzen abzustellen.

**Comment by geramy92** [comment]
ICh habe doch gerade eben schon gesagt dass räder und optischer schaden so nicht machbar sind lies bitte den ganzen satz nicht nur die hälfte
