### ISSUE TITLE
Idee | Interiormarker in Datenbank

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#16]
Hey.
Vielleicht könnte man alle Interiormarker in eine Datenbanktabelle eintragen. (Ein- & Ausgang von zB. Stadthalle, LSPD...) um alles übersichtlicher zu machen.
Liebe Grüße. ;)

**Comment by FFrozen** [comment]
Sehe ich selber als unnötig - 
Würde eh nur der Inhaber bzw 1-2 Personen mehr sehen, die sollten schon wissen wo die Marker sind
