### ISSUE TITLE
Ticket im SAPD

### ISSUE THREAD

**Issue by DominicaliasBroS** [TerraTex-Community/TerraTex-Reallife-Reloaded#165]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------

Eigentlich sollte das Ticket in die Frakkasse des SAPDs gehen, allerdings verschwindet das bezahlte Geld für das Ticket. 
http://www.pic-upload.de/view-31453222/mta-screen_2016-08-14_00-25-00.png.html

**Comment by geramy92** [comment]
Es ist Absicht dass nur automatische Beträge in die Fraktionskasse gehen.
Es ist daher also auch Absicht dass kein Geld eines /ticket in die Fraktionskasse geht,
