### ISSUE TITLE
/addruhe bug

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#17]
Wenn man /marka, /markb und anschließend /addruhe macht, wird die Ruhezone zwar erstellt. Wenn ich aber in die erstellte Ruhezone rein & rausgehe dann kommt die Meldung im Chat nicht.. (Du hast eine Ruhezone betreten. Hier herrschen folgende Regeln:...)

**Comment by geramy92** [comment]
Die Funktionen heißen zukünftig: /setRZoneCorner [1|2] und /delRZone [ID]

**Comment by geramy92** [comment]
Ist der Bug im alten Script aufgetreten oder ist dieser auch im neuen Script...?

**Comment by BritishEye** [comment]
Ist auch im neuen Skript so.

**Comment by geramy92** [comment]
mh strange ... codetechnisch sollte es funktionieren....
okay muss ich später noch mal austesten

**Comment by geramy92** [comment]
Hast du schonmal geschaut ob es irgendwelche Fehler in der Server- oder Clientconsole dazu gibt?

**Comment by geramy92** [comment]
Problem solved.
Achtung: Wenn in der Datenbank Ruhezonen mit einer Negativen X oder Y Size stehen, so müssen diese gelöscht und neu erstellt werden.
