### ISSUE TITLE
Kostenerhebung beim rearmen + Anpassung der Kosten für WT und GT.

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#171]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [X] Question

Rearmen sollte der Fraktion Geld kosten (PD/NAME).
Wenn möglich Rangabhängige Kosten aufgrund der unterschiedlichen Ausstattungen, sowohl guten als auch bösen Fraktionen.

Kosten für WT auf 30-40k$ erhöhen, und GT kosten auf 30-40k$ erhöhen (wenn zu hoch, anpassen).

**Comment by HammelKen** [comment]
GT auf 80-100k erhöhen wenn er 100k bringt klingt schon irgendwie falsch. Rearmen der Staats Fraktionen sollte meiner Meinung nach kostenfrei bleiben weil sie im realen Leben ja quasi auch vom Staat finanziert werde. Ein Komplett voller WT kostet 25k das ist wie ich finde mehr als genug.
