### ISSUE TITLE
Nach dem schließen von /profile kann man nicht mehr laufen/fahren!

### ISSUE THREAD

**Issue by MrHufferson** [TerraTex-Community/TerraTex-Reallife-Reloaded#173]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
Diesen Bug finden wir auf dem Server^^
1. Gebe /profile in den Chat ein. ( ein Fenster öffnet sich )
2. Versuche dieses Fenster zu schließen, indem man auf den roten "Schließen" Button klickt.

Nun kann man nicht mehr laufen/fahren.

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
Nein.

**Comment by StalkerGER** [comment]
Drück einfach mal Alt-Gr.
