### ISSUE TITLE
DFT Teleport

### ISSUE THREAD

**Issue by DominicaliasBroS** [TerraTex-Community/TerraTex-Reallife-Reloaded#175]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Durch den neuen DFT abschlepper kann man User die in privat Fahrzeugen sitzen abschleppen, sobald man dies gemacht hat, sitz der Spieler samt Fahrzeug auf dem DFT drauf, und wenn man dann das Fahrzeug dann auf eine Stelle wzb. SEK Basetor stellt, dann fällt das Auto runter, allerdings ist es noch auf dem Dft drauf (User kann trotzdem wegfahren). Man muss erst nochmals auf den DFT klicken und auf das Symbol abladen, dann ist der User samt Fahrzeug richtig unten.

**Comment by scriptcodeDE** [comment]
Should be closed
