### ISSUE TITLE
LSPD - Verhörzimmer

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#186]
## What type of report is this?

set the x for the correct type
- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question
## Where can we find this Issue? What are the Steps to reproduce this Bug?

Im zweiten Raum, links vom Marker durch die Tür, kann man durch den Boden fallen.

**Comment by scriptcodeDE** [comment]
@geramy92 Hast du ne Idee, wo im Script/DB ich die Marker für das Verhörzimmer finde?

**Comment by Johann0215** [comment]
done
