### ISSUE TITLE
Protokoll von Geramy's Idee

### ISSUE THREAD

**Issue by DominicaliasBroS** [TerraTex-Community/TerraTex-Reallife-Reloaded#187]
What type of report is this?
----------------------------
set the x for the correct type

- [] Bug / Error Report
- [x ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
Idee von Geramy protokoliert.: Blitzerlimit ab dem geblitzt wird auf 100 Km/h erhöhen.
Blitzer beschädigen/zerstören können  (sollte eine Meldung für jeden PDler erscheinen, dass BlitzerYX von SpielerXY zerstört wurde und dieser sollte dann auch ein Wanted bekommen z. B. Sachbeschädigung oder einfach warten bis das neue Wantedsystem da ist und dann dies erst da einfügen ?) und das der zerstörte Blitzer dann eine gewisse Zeit nicht mehr blitzen kann. 
Wahrscheinlichkeit dass man von dem jeweiligen Blitzer beim durchfahren erwischt wird auf 15 % senken.

**Comment by geramy92** [comment]
beim lewtzten soll die 10%ige chance bestehernb nicht grblitzt zu werden also genau umgekehrt
