### ISSUE TITLE
Tankstelle "Reparatur"

### ISSUE THREAD

**Issue by MegaEssen123** [TerraTex-Community/TerraTex-Reallife-Reloaded#191]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Zur Tankstelle fahren. 
2. Tanken.
3. Nachdem getankt worden ist, erscheint folgende Meldung:
**"Da das Fahrzeug in sehr gutem Zustand ist, wurde es nicht repariert."** (Das Fahrzeug war in einem schlechten Zustand.)

Ich dachte ich melde dies mal, da ich nicht weiss, ob dies bewusst ist.

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------

**Comment by scriptcodeDE** [comment]
Bereits gefixxt. Wird mit dem nächsten Update wirksam.

**Comment by scriptcodeDE** [comment]
Related to #181 & #184
