### ISSUE TITLE
GF Stopuhr

### ISSUE THREAD

**Issue by iHostiiX** [TerraTex-Community/TerraTex-Reallife-Reloaded#196]
Eventuell wäre ein Timer für den Gf ganz gut. Der oben rechts oder oben links die Zeit anzeigt wielange der GF noch geht

**Comment by Ceeserxx** [comment]
Oder wenn nicht direkt ein Timer mit sekunden ne nachricht bei noch 10, 5, 3 ,1 min wäre ne schöne sache.

**Comment by geramy92** [comment]
Ich würde eher sagen: Nein danke, denn dann wird es wieder mehr, dass die leute in der letzten Minute kommen.

**Comment by Ceeserxx** [comment]
Ginge es dann nicht eventuell so zu machen, dass man die nachricht nur bekommt, wenn man an dem angegriffenen Laden steht/in der nähe?
