### ISSUE TITLE
Andere Anzeige der Todesmarker in Innenräumen

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#198]
- [ ] Speichern der Positon des letzten Betretenen Markers
- [ ] Hinzufügen zu /hin
- [ ] Hinzufüge zu Betreten des Markers aus object_teleport_markers
- [ ] Andere Anzeige der Marker

Todesmarker sollen zum Eingang des Innenraums führen. Bei betreten des Innenraums soll der ursprüngliche Marker angezeigt werden.

**Comment by scriptcodeDE** [comment]
- /hin
- Innenraum

**Comment by scriptcodeDE** [comment]
@geramy92 Sind alle Innenräume in einer anderen Dimension/Interior und nur die "Aussenwelt" bei 0 ?

**Comment by geramy92** [comment]
bis auf ganz wenige ja
es gibt ein paar ganz ganz wenige die interior/dimension 0 haben

**Comment by Maxx4u** [comment]
Speichern der Position vom letzten Marker könnte ein Problem sein, wenn der Spieler TTeam ist und sich aus welchen Grund auch immer, wegteleportiert hat.

**Comment by scriptcodeDE** [comment]
Ist mir auch schon aufgefallen... Besonders, wenn man mal eben im Interior reloggt oder ähnliches. Somit verschieb ich das Projekt aus aktuellem Zeitmangel erstmal.
