### ISSUE TITLE
Bug bei Hausmarker

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#20]
Es ist möglich, von jedem Hausmarker aus auf die eigene Hauskasse usw zuzugreifen.
Es wird im code einfach bei einem Hausmarker die Hausid des Users abgefragt.

**Comment by geramy92** [comment]
Das stimmt so nicht,

```
local haus=haeuser[hID]
if(haus:isPlayerInHouse(thePlayer) or haus:getPlayerDistance(thePlayer))then
```

Fragen ab, ob derjenige an SEINEM Hausn ist. Wenn /hkasse dennoch geht.
Der Fehler war eher, dass ich dort vergessen habe die Entfernung mit irgendwas zu vergleichen
