### ISSUE TITLE
PD - DFT Abschlepptruck - Polizeicomputer

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#200]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
PD DFT Abschlepptruck wird zwei mal im Polizeicomputer angezeigt

**Comment by scriptcodeDE** [comment]
Should be closed
