### ISSUE TITLE
Preise 24/7 und Tanken Bezahlung

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#201]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Preise ab ID 6 im 24/7 verschoben, Hamburger wird zbsp immer noch für 1,95 angezeigt, kostet aber 4,95 usw.

Wenn man nicht genug Geld auf der Hand hat, wird der Tankpreis vom Bankkonto abgebucht.

**Comment by geramy92** [comment]
wenn bitte in getrennten Tickets.
