### ISSUE TITLE
PD - Gefängniszeit bei Tötung ist noch auf alten Stand

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#203]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
Tötung eines Gesuchten führt zu einer alten Knastzeit.
7 statt 10 Minuten usw.

**Comment by geramy92** [comment]
7 Minuten ist die neue
10 Minuten ist uralt

Wie man hier sehen kann stimmt es im Script:
https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/blob/master/terratex_reallife/ENVIRO/spawn_kill_system/kill.lua#L177
