### ISSUE TITLE
Bezahlung beim Tanken

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#208]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Wenn man nicht genug Geld auf der Hand hat, wird der Tankpreis vom Bankkonto abgebucht.

**Comment by Maxx4u** [comment]
Wird vorübergehend so gelöst, das beim Tanken zuerst das Bargeld überprüft wird, wenn nicht genug vorhanden, dann die Bank.
Wenn das über Bank bezahlt wird, werden zusätzliche 5% bearbeitunggebühr verrechnet.
