### ISSUE TITLE
Ausfall des Geschwindigkeitsbegrenzers in der Ruhezone.

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#21]
Man kann außerhalb einer Fraktion, und innerhalb einer Fraktion mit dem Privatfahrzeug, über die 30 KM/h geschwindigkeitsbegrenzung in der Ruhezone beschleunigen.

**Comment by geramy92** [comment]
würdest du mir auch noch mitteilen wie?

**Comment by geramy92** [comment]
fixed
