### ISSUE TITLE
Erschießen im Auto

### ISSUE THREAD

**Issue by HammelKen** [TerraTex-Community/TerraTex-Reallife-Reloaded#210]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Wenn man wem in einem Auto erschießt fällt der Wagen durch die Map, spawnt und fällt wieder durch die map. So lange bis die Leiche respawnt.
2. Jemanden im Auto erschießen

**Comment by geramy92** [comment]
ist ein MTA Bug
ich bin mir nicht sicher wie man das so fixen soll

... höchstens in dem ein toder aus dem fahrzeug gekickt wird....
