### ISSUE TITLE
"Cooldown" für /find befehl

### ISSUE THREAD

**Issue by Ceeserxx** [TerraTex-Community/TerraTex-Reallife-Reloaded#211]
What type of report is this?

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Es wäre schön, wenn der /find befehl für Zívis sowie fürs SAPD nur begrenzt verfügbar ist, b.z. einmal alle 30 sekunden wäre eine schöne Zeit. Denn wenn man sich einfach /find Name bindet ist auch Handy ausschalten ziemlich sinnlos und außerdem können mit dem "cooldown" nicht innerhalb von ner halben minute alle Spieler der Bösen fraktionen durchgefindet werden wer gerade z.b. einen WT fährt.

**Comment by DominicaliasBroS** [comment]
30 Sekunden ist übertrieben, finde den Cooldown sowieso sinnlos, da wenn das Handy aus ist, wird es trotzdem nur begrenzt angezeigt und der Marker bleibt ja auch für 4-7 Sekunden da, somit ist es fair genug.

**Comment by Maxx4u** [comment]
Und solange der Marker da ist, kann sowieso kein anderer gefindet werden.
