### ISSUE TITLE
Glen-Park verschönerung

### ISSUE THREAD

**Issue by Ceeserxx** [TerraTex-Community/TerraTex-Reallife-Reloaded#212]
What type of report is this?
----------------------------
- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
https://forum.terratex.eu/index.php?thread/4711-wir-suchen-w%C3%BCnsche-ideen-zum-mappen/
Im Spoiler unter punkt 1.

Map download: http://www.mediafire.com/download/sncq394377eckrm/Glen-Park.map

**Comment by StalkerGER** [comment]
Ganz ehrlich, zu viele Bäume und Büsche. Sieht alles auch etwas chaotisch aus nach dem Motto "schnell alles reinkloppen damit wir schnell fertig sind".
Vorallem weil ihr wohl von jedem existierenden Baum im Spiel einen da reingebaut habt.

Ich hätte es evtl etwas "romantischer" gemacht, weniger Bäume und Sträucher und geguckt das alles auch super zusammen passt, nach dem Motto "weniger ist mehr". Der Ort soll ja dann zur erholung dienen, und evtl ein Treffpunkt sein.

Ist aber nur meine Meinung.

**Comment by scriptcodeDE** [comment]
Also wenn man drin steht find ichs echt schön, aber wenn man von Aussen schaut, wirken einige Bäume zu übertrieben hoch. Von aussen wirkt es wie eine Art Jungle mitten in der Stadt. Ansonsten echt gut.

**Comment by geramy92** [comment]
#267
#266
