### ISSUE TITLE
Parkhaus mit Motorrad fällt man unter die Map beim rausfahren

### ISSUE THREAD

**Issue by xerox8521** [TerraTex-Community/TerraTex-Reallife-Reloaded#214]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Fahre mit dem beliebigen Motorrad ins Parkhaus am Pershing Square
2. Versuch mit dem Motorrad rauszufahren.
3. Man wird vom Bike geschmissen und fällt unter die Map dabei verschwindet das Bike irgentwo. Wo genau ist mir unbekannt.

**Comment by geramy92** [comment]
das lässt sich nicht wirklich beheben, daher sollte man das auch nicht tun

**Comment by StalkerGER** [comment]
Hm, wie genau werden die Fahrzeuge denn geportet? Evtl ist die Z (müsste höhe sein) zu niedrig eingestellt? Oder kann man die Personen für den Port aufs Motorrad freezen?
