### ISSUE TITLE
Fahrzeuglöschung wenn Fahrzeug von einem anderem User ins Wasser gefahren wird.

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#218]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Wenn zbsp ein User mit dem Fahrzeug eines anderen ins Wasser fährt, und der Fahrzeughalter nicht in der Nähe ist, sollte das Fahrzeug ebenfalls zerstört und nicht respawnt werden.

**Comment by geramy92** [comment]
Und warum? Damit jeder die Fahrzeuge anderer kaputt machen kann? Was ist da
der Sinn?

Am 19.08.2016 00:32 schrieb "StalkerGER" <notifications@github.com>:

**Comment by iHostiiX** [comment]
Das sehe ich genau so. Es gibt genug idioten die sowas machen.

**Comment by Ceeserxx** [comment]
Story dazu: Ich hatte iHostiix NRG beim Truckerjob versenkt im Wasser bei einem unfall mit nem Truck auf der Brücke. Ich bin zu Maxx und Stalker in den Channel und die sagten, die sei nichtmehr zu retten. Einer sagte noch "ne die respawned von alleine". 
Da es ein Reallife Server ist kann man eigentlich sagen ja. Aber wenn man einmal daran denkt, dass dann permanent Leute am Truckerjob Fahrzeuge ins Wasser schieben würden oder wenn einer mal dein Auto irgendwo, seis dich rauszieht oder du vergisst es abzuschließen, dann kann jeder das Auto zerstören. Von daher kann man das wirklich nicht machen oder jeder fährt freiwillig nurnoch mit Clovern.

**Comment by StalkerGER** [comment]
Frag Maxx, ich bin nur der überbringer der Botschaft.
