### ISSUE TITLE
Neues / Überarbeitetes AKW mit neuen Ideen

### ISSUE THREAD

**Issue by Ceeserxx** [TerraTex-Community/TerraTex-Reallife-Reloaded#219]
What type of report is this?
----------------------------
- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [x] Refactoring / Removerequest
- [ ] Question

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
https://forum.terratex.eu/index.php?thread/4711-wir-suchen-w%C3%BCnsche-ideen-zum-mappen/#post22280
Im spoiler unter punkt 3.

Folgende ideen, die gesrciptet werden müssten: Das Gesamte AKW könnte als Sperrzone markiert werden dazu Koordinaten wären von X: 2810.9006347656, Y: -2565.025390625, (Z:13.632813453674) bis X: 2575.1752929688, Y: -2752.5134277344, (Z: 13.620732307434) , in der man **3** Wanteds bekommt, wenn man sie betritt mit 5 oder 10 sek vorwarnung.
Für die Kisten, die neben dem AT Spawn dachte ich mir, dass jede Kiste als jeweils 5 Einheiten zählt ( und sie spawnen bei: 1 Kiste=5, 2 Kisten=10 etc.. also 4 Reihen mit je 5 Kisten. Somit könnte ein Mitglied einer bösen Fraktion dort einbrechen um zu gucken, ob das PD in nächster Zeit einen AT fahren muss (Bsp: 9 kisten = 45 Einheiten) und könnte sich vorbereiten, wenn dort viele Kisten stehen.
Zum AT: Wenn die Kisten dort Spawnen kann beim Start eines ATs eine wartezeit von 15 oder 30 sekunden eingebaut werden mit einer Meldung "Ein Atomtransport wird beladen.." für alle bösen Fraktionen. Nachdem die Wartezeit zuende ist sollten pro 25 Einheiten die Kisten, die dann je 5 Einheiten zählen despawnen, also 5 Kisten pro AT (gelöscht werden) und der AT ist startbereit, wobei dann erst im Chat für alle steht, dass ein Atomtransport auf dem Weg ist.
Zudem wäre es schön, wenn die Schranke (auf den Screens zu sehen) zum "2. Teil des AKW's" nur von PD'lern geöffnet und geschlossen werden kann mit dem standartbind (/mv), statt dauerhaft geöffnet zu sein.

Günther (scriptcodeDE) hat zugesagt, dass es mit den Kisten Spawnen kein Problem sein würde und sich gerne das Scripten annimmt ;) ;)
Die position der 1. Kiste ist X: 2683.978515625 ; Y: -2676.6259765625 ; Z: 12.497420310974
Jeder Kiste benötigt X +1.6 und Y -1.6

Map Download: http://www.mediafire.com/download/89wvaf5n5l159t6/akw.map

**Comment by scriptcodeDE** [comment]
- [x] Finished development on Devserver
- [ ] Must be tested again

**Comment by scriptcodeDE** [comment]
Aufgrund von aktuellen Tests mit dem Deaktivieren der Berechnung von verdeckten Objekten, kann das AKW erst in 1 bis 2 Wochen eingebaut werden. Ist aber fertiggestellt. Der Timer wurde auf Wunsch von Geramy entfernt. Ich habe noch ein paar Zäune hinzugefügt, sowie das andere Tor in ein Tor, dass sich öffnen lässt verwandelt.
