### ISSUE TITLE
Innenraummarker buggen

### ISSUE THREAD

**Issue by DarkCitizen** [TerraTex-Community/TerraTex-Reallife-Reloaded#22]
Die Marker von Gebäuden geben die Meldung aus "teleport disabled". Es erfolgt trotzdem eine Teleportation. Beim Verlassen kommt es nun bei einigen Markern vor, dass man in der falschen Dimension bleibt. 
Wo ich es getestet habe und es nicht geht sind die Stadthalle und die Grovebase.
Das LSPD(Haupteingang) funktionier.

**Comment by geramy92** [comment]
"teleport disabled" ist nur ein debug den ich vergessen hatte zu deaktivieren. Das ist richtig, dass dieser kommt. Der verhindert, dass der Empfangsmarker einen wieder zurückportet.

Was die Fehler angeht, wäre es lieb wenn du genauer werden würdest. Sprich:
-> Welcher Marker? Was geht nicht? (Interior, Dimension oder Port)
