### ISSUE TITLE
PDler mit Wanteds begehen bei Logout Offlineflucht

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#223]
Wenn man als PDler Wanteds hat (z.B. weil ein Kollege einen Trollen will), und man offline geht erhält man Offlineflucht (auch wenn man alleine in der Umgebung ist)

**Comment by StalkerGER** [comment]
Wenn PDler sich gegenseitig Trollen und Wanteds geben, sollten diese nochmal überlegen, ob sie für das PD geeignet sind.

**Comment by scriptcodeDE** [comment]
War mir nur aufgefallen beim Testen auf meinem Devserver
