### ISSUE TITLE
PD - DFT Abschlepptruck - Teleport

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#234]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
Mit dem DFT können zumindest Fraktionsfahrzeuge mit Insassen teleportiert werden.
Beim Einsteigen von dem Fahrer ins Fahrzeug muss das Fahrzeug aufgeladen werden.
Danach kann das Fahrzeug einfach irgendwohin teleportiert werden.

**Comment by Maxx4u** [comment]
Und wie wir nun auch noch herausgefunden haben, kann man danach mit dem Fahrzeug FLIEGEN...

**Comment by scriptcodeDE** [comment]
Irgendwie versteh ich die Bug-Beschreibung nicht. Können wir ja mal Donnerstag im TS besprechen.
