### ISSUE TITLE
Bankautomat an der tanke in ls soll funktionieren

### ISSUE THREAD

**Issue by Jackass69** [TerraTex-Community/TerraTex-Reallife-Reloaded#235]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. [edit here]
2. .. 

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
> `log entries client`
> `log entries server`

**Comment by geramy92** [comment]
In LS gibt es viele Tanken....

**Comment by iHostiiX** [comment]
Es ist generell so das Viele Automaten stehen aber nicht alle Funktionieren. Ich könnte die mal abfahren und dir hier schreiben welche alle nicht gehen ;)

**Comment by Jackass69** [comment]
Das ist eine gute idee hosti aber ich meine den in der nähe vom pizzastack in ls

**Comment by scriptcodeDE** [comment]
@iHostiiX 👍  Kann diese dann gerne einbauen

**Comment by geramy92** [comment]
das Thema ist, dass es nicht m,öglich ist, diese mit Standardautomaten einzubauen.
Es gehen nur automaten, die wir via Script spawnen. Man müsste also mal folgendes tun: 

- [ ] Aus den Mapdatein alle automaten raussuchen und in SYSTEM/banksys/banksys.lua einfügen und aus Mapdatei löschen
- [ ] Standardautomaten von GTA:SA löschen und ebenfalls im Script neu erstellen in SYSTEM/banksys/banksys.lua

**Comment by iHostiiX** [comment]
Oke. Die an der LS Tanke oben am BSN geht aufjedenfall nciht. Kann man da nicht einen drüber packen ?

**Comment by geramy92** [comment]
nein kann man nicht

**Comment by scriptcodeDE** [comment]
Was wäre, wenn man in der banksys.lua, statt in der Tabelle der Automaten das angeklickte Objekt zu finden, prüfen würde `if (getElementType(source) == "object" and getElementModel(source) == 2942) then` ?

**Comment by geramy92** [comment]
bin mir grad nicht sicher wie ich das Script geschrieben habe, aber das könnte man ggf. auch machen, ja. Allerdings würde das, soweit ich weiß immer noch nicht mit Standard Automaten funktionieren.

Bzw. Müsste man das mal austesten, aber ich meine das es nicht mit Standardobjekten so leicht geht, hatte das Problem mal an anderer Stelle.... aber sicher bin ich mir grad nicht

**Comment by geramy92** [comment]
oklay ich muss sagen ich bin grad zu blöd einen Automaten aus dem Standard GTA zu finden .... aufjedenfall für die gemappten geht es ja

**Comment by scriptcodeDE** [comment]
Hab ich auch gerade getestet, habe aber auch keine Ahnng, wo ein Standard-Automat sein soll :D

**Comment by scriptcodeDE** [comment]
Gleiche Überlegung: Könnte man doch theoretisch auch für die Sprunk-Automaten so machen oder? Hab schon einige Automaten gesehen, die nicht funktionieren.

**Comment by scriptcodeDE** [comment]
Hmm.. Ok anscheinend werden vom Script nur die ColShapes erstellt und die Automaten kommen aus Maps/Standard-GTA.

**Comment by geramy92** [comment]
jop Sprunkund bus besteht das problem das es kein getStandardElements() funktion gibt :P getElementsByType gibt ja leider keine aus dem Standard zurück (bzw. die für die colshapes)

**Comment by geramy92** [comment]
ich hab mal inzwischen das Issue geclosed da dieses ja erledigt ist... Wenn wir eh kein Standardautomat finden ;-)

**Comment by scriptcodeDE** [comment]
Haha ja :D
