### ISSUE TITLE
Die Nagelbänder wiedereinführung

### ISSUE THREAD

**Issue by MrHufferson** [TerraTex-Community/TerraTex-Reallife-Reloaded#236]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [X] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Wie wäre es, wenn man mal wieder die Nagelbänder für das SAPD einführen würde?
Man fährt mit dem Auto über das Nagelband und die Autoreifen werden platt.
Diesmal sollten sie aber richtig funktionieren.

**Comment by scriptcodeDE** [comment]
- [ ] Ein passendes Objekt finden
- [ ] Berechnung X und Y Koordinaten der Eckpunkte des Objektes anhand der Drehung des erzeugten Objektes für createColPolygon
- [ ] Bei Betreten des Cols prüfen, wie weit Entfernt das Fahzeug ist (wegen Flugzeugen)
- [ ] Bei Betreten alle Reifen zerstören (setVehicleWheelStates)
(Geramy weis mich mal zu :) )

**Comment by geramy92** [comment]
wird so nicht funktionieren 

zum einen sollten die reifen nicht schon 5 meter vor dem nagelband platzen wodurch die col wie du schon schreibst so groß wie die objekte sein sollte.... das hat aber ein anderes problem: Wenn man schnell genug drüber fährt (zB mit Infernus) reagieren solch kleine colshapes nicht mehr (bei markern das selbe).....

**Comment by scriptcodeDE** [comment]
Wollte das Clientseitig checken (onClientRender)

**Comment by geramy92** [comment]
mh hatte ich auch mal versucht .... weiß gar nicht mehr warum ichs gelassen habe, ich glaub weil ich da nur isElementInColShape benutzt habe oder so.... wenn dus via positionen berechnest könnte das gehen ... in diesem zusammenhang wäre natürlich cool, wenn mans hinbekäme das aufgrund der berechnung nur die reifen platzen, die wirklich das band berühren :P

**Comment by scriptcodeDE** [comment]
Das wäre dann aber auch nur sehr ungenau (woher soll ich die Positionen der Reifen wissen? :D Ich könnte das Auto rein mathematisch nur in 4 Teile aufteilen (für die verschiedenen Reifen)

**Comment by scriptcodeDE** [comment]
Wobei: https://wiki.multitheftauto.com/wiki/GetVehicleComponentPosition Ich hab nur keine Ahnung wie ich die Reifen anspreche

**Comment by geramy92** [comment]
anders habe ich mir das auch nicht gedacht :P 

DIe Funktionen könnten Abhilfe schaffen:

https://wiki.multitheftauto.com/wiki/GetElementMatrix
https://wiki.multitheftauto.com/wiki/GetElementBoundingBox

**Comment by geramy92** [comment]
https://wiki.multitheftauto.com/wiki/GetVehicleComponentPosition  ist für Tuning teile ;-)

**Comment by scriptcodeDE** [comment]
Habe gerade mal dieses Script ausprobiert: http://pastebin.com/cBmmjq62
Screen: https://pl.vc/ups25

**Comment by scriptcodeDE** [comment]
Somit sehr präzise möglich :P

**Comment by geramy92** [comment]
na dann
hab ich mich halt mal getäuscht 
good luck :P

**Comment by scriptcodeDE** [comment]
Aktueller Stand: Alles funktioniert einwandfrei, bis auf das Erstellen getCursorPosition() spuckt beim ersten Erstellen in einer gerade erst geladenen Zone nur Blödsinn aus (MTA-Bug). @geramy92 hast du eine Ahnung wie ich das beheben kann (Cursor neben Spieler, ausgerechnete Distance: ca. 300, Bei ausgabe der worldx, worldy und worldy von getCursorPosition: komplett andere Koordinaten, als wäre der Boden nicht da)

**Comment by geramy92** [comment]
machs nicht mit cursor
einfach spieler position und rotation und dann vor den seine Füße spawnen

**Comment by scriptcodeDE** [comment]
ok mit processLineOfSight habe ich die richtigen Koordinaten, aber das Object der Vorschau ist irgendwie unsichtbar beim ersten mal

**Comment by scriptcodeDE** [comment]
vllt. muss ich das Objekt streamen

**Comment by scriptcodeDE** [comment]
Ich denke deine Lösung ist echt die Beste ;(
