### ISSUE TITLE
Prestigefix nicht gefixxt. :p

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#24]
"Du hast nicht genug Geld deinem Konto um dieses Prestigeobject zu kaufen!"
sollte eigentlich heißen
"Du hast nicht genug Geld AUF deinem Konto um dieses Prestigeobject zu kaufen!"
Nur zu Erinnerung. c:

**Comment by geramy92** [comment]
gefixxt ist es nur ein Wort ist verloren gegangen ?
