### ISSUE TITLE
24/7 - Kaputt

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#242]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
Der innere Marker im 24/7 funktioniert nach dem Update nicht mehr.

**Comment by scriptcodeDE** [comment]
Seltsam... Hatte beim Testen alles einwandfrei funktioniert

**Comment by geramy92** [comment]
mh bezweifle ich.... es geht um die marker an dennen sich der einkauf öffnet,,, und die hatten in deiner variante gar keinen eventhandler zum einkaufen... ich glaube du hast sowieso ein paar bauteile des scriptes missverstanden

Ist aber auch egal ich hab es nochmal überarbeitet, dass es jetzt geht ;-)
