### ISSUE TITLE
/sos funktion des PDs

### ISSUE THREAD

**Issue by Vanity1206** [TerraTex-Community/TerraTex-Reallife-Reloaded#245]
## What type of report is this?

set the x for the correct type
- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Wenn man /sos macht wird die Position dem Innendienst mitgeteilt. Momentan haben wir keinen ID, daher würde ich bitten das /sos den aktuellen Streifen mit geteilt wird.

**Comment by scriptcodeDE** [comment]
Und wie stellt man fest, wer die aktuelle Streife ist? Wenn nur allen PDlern, die duty sind.

**Comment by geramy92** [comment]
Mir gefällt es sowieso nicht so sehr, wenn man das gleich so offen jeder sehen würde / wie du schon sagtest, weiß man ja nicht wer Streife ist. Ich hätte da aber schon eine Idee, das ganze ggf, als neue Funktion zusätzlich in den neuen Polizeicomputer einzubauen :)

**Comment by Snowfighta** [comment]
Wie wäre es, wenn die Meldung an alle Polizisten geht, die duty und in einem Polizeifahrzeug sind?

**Comment by LightningKirito** [comment]
Gibt es nun eine Version der /sos-Funktion oder muss eine angefertigt werden?

**Comment by geramy92** [comment]
/sos gibt es schon lange nur diese Änderung nicht, sonst hätte ich das Ticket schon geschlossen ;-)
