### ISSUE TITLE
Tankstelle LS/LV 24/7 Marker

### ISSUE THREAD

**Issue by Vanity1206** [TerraTex-Community/TerraTex-Reallife-Reloaded#246]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Beim 24/7 an der Tankstelle LS/LV wird man unter die Map geportet beim betreten. Danach stirbt man, weil man irgendwo über Blueberry ist und beim aufprall stirbt

**Comment by scriptcodeDE** [comment]
Vor Geramys Bugfix hats funktioniert. Ich schau mir das mal an.

**Comment by scriptcodeDE** [comment]
Ok ich nehme alles zurück :D anscheinend wurde irgendwas nur seltsam überschrieben vor Geramys Fix. Sry :D

**Comment by geramy92** [comment]
an den koordinaten hatte ich nichts geändert nur den ganzen rest ;-)
