### ISSUE TITLE
Saubere Fahrzeug-Texturen

### ISSUE THREAD

**Issue by BOBAtm** [TerraTex-Community/TerraTex-Reallife-Reloaded#249]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Eine kleine Änderung in der Datei vehicle.txd unter [...]\GTA San Andreas\models\generic sorgt für saubere Texturen auf allen Fahrzeugen. Die selbst bearbeitete Datei ist unter folgendem Link aufruf- und herunterladbar:
https://drive.google.com/file/d/0B7NYDTbZw_H_cmJQeTEzSVJxNjA/view?usp=sharing

**Comment by geramy92** [comment]
nicht via MTA:SA machbar.
