### ISSUE TITLE
Fahrzeuge flippen

### ISSUE THREAD

**Issue by BOBAtm** [TerraTex-Community/TerraTex-Reallife-Reloaded#250]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Fahrzeuge können mit /vehflip aufgerichtet werden.
Der Befehl soll einen Cooldown von mehreren Minuten bekommen, um Spam zu vermeiden.

**Comment by geramy92** [comment]
unrealistisch
