### ISSUE TITLE
Waffentruck - 

### ISSUE THREAD

**Issue by Snowfighta** [TerraTex-Community/TerraTex-Reallife-Reloaded#254]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
Waffentruck dreht sich nicht um, wenn man sitzen bleibt.

**Comment by DominicaliasBroS** [comment]
Doch, nur bei dem der den WT gestartet hat.

**Comment by geramy92** [comment]
man muss nicht mehr im WT sitzen bleiben, von daher ergibt der letzte kommentar dann wenig sind.....

**Comment by Snowfighta** [comment]
Gut zu wissen^^ dann sollte ich nicht mehr auf Geramy hören :P

**Comment by geramy92** [comment]
@Snowfighta dann ignoriere ich mal deine Beiträge in Zukunft wegen Verblödung

Ich wiederhole mich nochmal: DIE FUCKING FUNKTION FRAGT NIE AB WER GESTARTET HAT UND WER NICHT. DAS WIRD NICHT MAL GESPEICHERT WEIL ES DEM SCRIPT SCHEIßEGAL IST.

Wenn es da funktioniert hat, ist das reiner zufall. Wie ich es bereits kommentiert habe nach Bros.

Es gibt dafür nur zwei Möglichkeiten warum es nicht geht und beides wäre sehr strange:
1. Das Script kann manchmal, warum auch immer nicht auslesen wie viel Leben das Fahrzeug noch hat
2. oder: Der Trigger für den Schaden eines Fahrzeugs funktioniert, warum auch immer manchmal nicht
