### ISSUE TITLE
Lizenzensystem auf TT anpassen 

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#259]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Das Lizenzsystem ist nicht weit genug ausgeführt. Genaues konnte ich nicht testen.

Folgendes Szenario. Spieler besitzt einen Motorradführerschein und seinen Autoführerschein. Er verliert durch StVo Punkte seinen Autoführerschein. Nun möchte er sich ein Motorrad kaufen damit er weiter mobil ist (In dem Fall war es die Faggio). Der Spieler konnte sich das Motorrad nicht kaufen aufgrund das er die benötigten Lizenzen nicht besitzt (obwohl er die Motorradlizenz besitzt).

**Comment by DominicaliasBroS** [comment]
? Wie soll man dann Motorräder fahren, wenn die meisten abgeschlossen sind ? Was sollte das bringen ?
Und den Flugjob kann man meines Wissens nach garnicht starten, wenn man nicht beide Lizenzen hat.

**Comment by scriptcodeDE** [comment]
Bei zu vielen StVo-Punkten sollten meiner Meinung nach sowieso alle Lizensen zum Fahren abgenommen werden (Auto, Motorrad, Truck, Spezial)

**Comment by Shariner** [comment]
Abgesehen davon das man in jedem Land keinen Führerschein benötigt um ein Auto/Motorrad oder Flugzeug zu kaufen. Eigentümer kann man immer sein. Das macht die Sache hier trotzdem nicht unnötig. 

Würde dich aber folgendermaßen kommentieren. Wir sind ein Reallife/Roleplay Server. Wir machen aber nicht die 1:1 Realitätsgetreue RL Nachbildung. Da man auf dem Server ohne Führerschein auch gleich wieder offline gehen kann wäre es ein großer Nachteil für den Server wenn alle Lizenzen aufeinmal abgenommen werden würden, abgesehen von den Kosten für die Wiederbeschaffung. (Man denke mal an Flug Lizenzen)

**Comment by geramy92** [comment]
Ich sehe da mal folgende Tasks:
1. Er sollte wenn er den Autoführerschein verliert ebenfalls den Motorradschein verlieren (selbe StVO)
2. Die Überprüfung beim Kaufen (auch beim Faggio) ist nach wievor fehlerhaft (warum auch immer)

**Comment by geramy92** [comment]
gefixed mit einem der patches von 1.2.0
