### ISSUE TITLE
Neue Tankstelle und 24/7 Eingang Bug --> Nullspawn

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#263]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Neue gemappte Tankstelle. --> 24/7 betreten --> Nullspawn in der Höhe.
2. .. 

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
> `log entries client`
> `log entries server`

Hab nen Video davon um sich das mal alles passend zu machen: 

https://youtu.be/1NHTKYVrNx0

**Comment by scriptcodeDE** [comment]
#247 Schon länger behoben, kommt aber erst mit nächstem Update
