### ISSUE TITLE
11880 Anrufweiterleitung zur Nummer

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#265]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Eingabe des Namens unter 11880 --> System gibt die Nummer aus und fragt ob man sofort dorthin verbunden werden möchte mit /weiterleitung (Suche noch nach einem besseren Befehl)

Die Weiterleitung dann kostenfrei - oder eben nicht. Kann man noch entscheiden wie man möchte und was sinnvoll ist. (Wie ist es denn im Reallife? Ich Ruf nie die Auskunft an :o) (Weiß nur das ich eine kostenfreie Nummer zur Ermittlung der Versicherung des Unfallgegners angerufen habe und die mich kostenfrei dahin verbunden haben)

Das wärs :)

**Comment by Ceeserxx** [comment]
Also ich fände es mit (halb)-automatischer weiterleitung richtig geil..
Mein Beispiel: 
Einfach /call 11880
Dann könnte man als nächstes einfach z.b. "call Snow" in den chat eingeben und der Anruf startet.
Wenn man nur "Snow" (also den Spielernamen) eingibt bekommt man wie vorher nur die Nummer angezeigt um später anzurufen oder ne SMS zu schreiben.

**Comment by scriptcodeDE** [comment]
Wie wärs, wenn man gefragt wird, ob man verbunden wird und dann "Ja" in den Chat eingibt? Mit Nein und /hangup wird dann abgebrochen.

**Comment by Ceeserxx** [comment]
Ich könnte mir das wie folgt vorstellen:
"/call 11880"
Willkommen bei der Auskunft! Wessen Telefonnummer möchten Sie wissen?
"rekz"
Die Nummer des Spielers lautet 471239. Möchten Sie verbunden werden? (Ja / Nein)
"Ja"
Sie werden nun verbunden. Es Klingelt...

oder

"Nein"
Du hast aufgelegt!
