### ISSUE TITLE
Eigenen Spawnort festlegen

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#268]
What type of report is this?
----------------------------
set the x for the correct type

- [] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Man soll /spawnchange here (oder etwas anderes) machen können und dann an der Position spawnen wo man /spawnchange here gemacht hat. Man kann diese Funktion eventuell auch für Gold kaufen können. (aber dann permanent würde ich sagen)
Ist halt nützlich wenn man einen Punkt hat der weit weg vom Noobspawn, seinem Haus oder der Fraktionsbase ist.
Und man sollte auch eventuell wieder /spawnchange job machen können.

**Comment by Philipp7655** [comment]
Also das mit /spawnchange Job finde ich eine gute Idee. Allerdings glaube ich dass man /spawnchange here ziemlich leicht ausnutzen kann um z.B. sich iwo hinzubuggen. Wenn das zb 5 Gold kostet wäre es ok wenn man was gegenüber die Bugs macht. Ansonsten wiegesagt /spawnchange Bus z.B. Ist gut wenn man nur jobben will.
