### ISSUE TITLE
Befehle verschwunden..

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#27]
Warum sind eigentlich Befehle wie /explode, /slap usw. aus dem Skript entfernt wurden?
Das Adminpanel (/admincmd oder im Inventar das AdminGUI) funktioniert auch nicht mehr.
Ist das so gewollt? Wenn ja, warum?

**Comment by geramy92** [comment]
Ganz einfach: Weil sie zum Großteil völlig sinnlos, deplatziert, veraltet oder fehlerhaft sind.

/slap ist übrigens nicht entfernt
