### ISSUE TITLE
Abrufbares News Wetter per Befehl

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#271]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Hinzufügen eines /wetter Befehls um Wetter jederzeit abrufbar zu machen. Am besten ebenfalls nur in der Nähe der Newsvans nutzbar (Satellitenverbindung aufbauen etc.)

**Comment by shayaaan** [comment]
Wäre ziemlich praktisch.

**Comment by geramy92** [comment]
Wichtige Wetter wechsel sieht der Newsreporter gleich. Später sieht man das Wetter mit den Augen. 
Einzige sind die Wetterevents: welcher allerdings vor der Stadthalle im I für alle gezeigt werden.
