### ISSUE TITLE
Bug Polizeicomputer - Spielerakte wird nicht aktualisiert

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#279]
Wenn ein Spieler mehr als 100% hat als Verbrechensstatus, aktualisiert der Computer die Akte erst nach erneuten Öffnen der Akte.

**Comment by MrHufferson** [comment]
Nicht nur bei 100%, sondern bei jeden dessen Akte mit /clear NAME gelöscht wurde!

**Comment by geramy92** [comment]
gehts etwas genauer`?

**Comment by geramy92** [comment]
Außerdem dauert es immer ein paar Sekunden bis sich was aktualisiert

**Comment by Snowfighta** [comment]
Also: Wenn ein Delikt gelöscht wird, wird der Kriminalitätsstatus beibehalten und die persönliche "Prozentanzeige" im HUD des Spieler wird erst nach einiger Zeit bzw. nach einem reconnect aktualisiert.

**Comment by geramy92** [comment]
Okay bis auf der Ursprüngliche Fehler alles gefixxt
