### ISSUE TITLE
/jailtime fehlerhafte ausgabe 

### ISSUE THREAD

**Issue by Vanity1206** [TerraTex-Community/TerraTex-Reallife-Reloaded#282]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Wenn man einen Spieler mit /jailtime checkt kommt bei jedem Spieler, egal ob er schon drin war, eine Zeit genannt wie lange er noch sitzen muss obwohl er nicht drin ist z.B.
Der Spieler NAME muss noch 0/0 Minuten im Knast sitzen. 
 Der Spieler NAME muss noch 0/30 Minuten im Knast sitzen.
Der Spieler NAME muss noch 0/1 Minuten im Knast sitzen.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Person für Notrufmissbrauch gestellt einknasten (4/4 minuten)
2. Warten bis die Zeit abgelaufen ist
3. jailtime checken (0/4 wird dort stehen)

**Comment by geramy92** [comment]
Sry aber ich verstehe gerade das Problem nicht wirklich. Die erste Zahl gibt an wie lange er sitzt und die letzte ist die Zeit für die er das letzte mal eingeknastet wurde bzw. wie lange er gesamt sitzen muss. Jemanden zu checken der nicht mehr im Knast ist, hat ja nicht wirklich einen Sinn bzw. so kann man ja noch nachprüfen, wie lange dieser saß, wenn er rauskommt.....  Oder zeigt es auch 0 an wenn er im Knast ist?

**Comment by Vanity1206** [comment]
Es gibt schon die richtige Zeit an wenn ich die Person checke. Aber es hat mich gestern verwirrt, als ich schauen wollte ob jemand im Alka ist den ständig stand dort 0/30. Kann sein das die Alka ausgabe fehlerhaft ist. Müsste ich aber selber noch einmal testen. Ich glaub vorher kam die Meldung "Die Person sitzt nicht im Gefängnis" 

+ selbst nach dem GMX ist immer noch die alte Zeit dort. Sollte die Zeit nicht wenigstens nach dem GMX wieder auf 0/0 gesetzt werden?

**Comment by geramy92** [comment]
es wird die letzte zeit in der datenbank gespeichert (auch Zeiten vor dem Update)

Die Frage ist: Soll man die letzte Knastzeit noch wissen, oder soll eher eine Meldung kommen "dieser sitzt nicht im knast" was aber auch bedeutet man sieht nie wie lange er saß wenn er rauskommt...

**Comment by Vanity1206** [comment]
Ich verstehe nur nicht was uns die alten Zeiten bringen soll. Das Versuche ich grade zu verstehen. 
Beispiel für Notrufmissbrauch 4/4
- Wenn ich ein Spieler die Zeit absitzt steht 0/4 da
- Wenn er die Kaution kauft steht 0/4 da
- Wenn ich ihn dearreste steht 0/4 da

Also mir fällt momentan nichts ein wofür ich die alten Zeiten gebrauchen könnte. 
Wir sehen dadurch ja nicht was er getan hat, wie oft usw.

**Comment by geramy92** [comment]
Vanity bitte noch mal von vorne. Wird da nun die richtige Zeit angezeigt oder nicht
Wenn ja kann ja wohl "Wenn ich ein Spieler die Zeit absitzt steht 0/4 da" nicht sein.

Die Erste Zahl stellt die aktuelle Knast zeit dar, die zweite die letzte vollständige Knastzeit

ein /jailtime macht **KEINEN SINN** wenn jemand drausen ist, außer er ist gerade aus dem Knast gekommen und man möchte nochmal wissen, wie lange er saß.

**Comment by Vanity1206** [comment]
Ich weis das ein /jailtime bei einer Person die draußen ist kein Sinn macht. Nur ich versuch immer noch zu verstehen was wir mit der alten Zeit anfangen sollen. Ich mein ich hab mich gestern für Notrufmissbrauch eingeknastet und heute stand wieder 0/4 da.

Es wird auch die restliche Zeit richtig angezeigt 
3/4 2/4 1/4 0/4 

Ich bin grade dezent verwirrt :D

**Comment by geramy92** [comment]
gut aber damit gibbet kein Bug sondern nur eine verwirrte Vanity :P

**Comment by Vanity1206** [comment]
Ja das hat mich schon ziemlich verwirrt, weil ich dachte es nicht gewollt. Du musst mir nur nachher noch die Frage mal im TS beantworten wozu ich alte Knastzeiten brauche :D
