### ISSUE TITLE
Casino BIZ

### ISSUE THREAD

**Issue by Anonymer123** [TerraTex-Community/TerraTex-Reallife-Reloaded#283]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

1. Es ist eher weniger ein Bug aber es handelt sich um das Casino BIZ. Es geht darum das ich von einigen Leuten gehört habe(dazu gehört auch der Besitzer) das, dass Casino BIZ unglaublich viel Geld auswirft was es eigentlich nicht tun sollte. Soweit ich weiß wurde es damals mal hochgeschraubt aber nicht mehr runter gesetzt. Nun bekommt TerrorKing einen Haufen Geld obwohl das nicht so sein sollte. Kein Wunder das er sich alles Leisten kann ohne zu Arbeiten. Ich bitte einmal das zu Kontrollieren, wäre ja sonst unfair gegenüber der anderen Spieler wenn dieser Junge Mann für nichts Millionen bekommt und wir dafür Hart arbeiten müssen.

**Comment by geramy92** [comment]
Ich muss sagen, ich hab das damals tatsächlich geändert, da ich es besessen habe und es fast nichts abgeworfen hat. 

Es sollte geändert werden, auf:
- nur 10% der Gewinne (oder weniger, wenn zu viel)
- Ausgaben müssen von der Bizkasse abgezogen werden (auszuzahlende Gewinne)
