### ISSUE TITLE
/tombupot Befehl

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#284]
- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Jeder soll mit dem Befehl folgende Ausgaben bekommen: Anzahl der Teilnehmer, Gekaufte Tickets und möglicher Gewinn.

**Comment by scriptcodeDE** [comment]
PS: Kann auch gerne von mir implementiert werden :)

**Comment by scriptcodeDE** [comment]
Alternativ: Ausgabe nur für Besitzer, damit dieser Werbung für die Lotterie machen kann (z.B. heute 50000$ im Pot)

**Comment by geramy92** [comment]
Ich würde eher sagen, dass man das zusätzlich in den Kauf Dialog einbauen könnte álá

Du hast bereits x Tickets gekauft und kannst noch x Tickets kaufen. Derzeit liegt der Po bei xxx $.

**Comment by scriptcodeDE** [comment]
Ggf. auch in den Kaufen-Dialog

**Comment by scriptcodeDE** [comment]
Fände ich eigentlich sogar sinnvoller ^^

**Comment by scriptcodeDE** [comment]
O wow das hattest du ja bereits vorgeschlagen :D I'm a genius

**Comment by geramy92** [comment]
Wie gesagt:

So wie ichs vorgeschlagen habe. Ggf. damit auch wer der schon alle Tickets gekauft hat nachschauen kann (aktuell kommt da ja nur chatbox oder show error mit das man schon maximale Tickets hat, zusätzlich für den den selben Dialog nur ohne Kaufoption

**Comment by scriptcodeDE** [comment]
Ich setze das mal so um :)

**Comment by scriptcodeDE** [comment]
Erstmal den Entwicklungsserver auf den aktuellen Stand bringen :D
