### ISSUE TITLE
Im Bluberry spawnen

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#285]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Dem Server joinen, solange keine letzten Spawnkoordinaten im System gespeichert sind
Nicht einloggen, sondern disconnecten
joinen
einloggen
=> Du spawnst im Bluberry

Behebung:
Abfrage bei Speichern der Koordinaten, ob Spieler eingeloggt ist

**Comment by geramy92** [comment]
Hinfällig durch #287
