### ISSUE TITLE
Gebrauchtwagenhändler als Fraktion

### ISSUE THREAD

**Issue by shayaaan** [TerraTex-Community/TerraTex-Reallife-Reloaded#290]
Hallo,
ich würde mir eventuell einen Gebrauchtwagenhändler als Fraktion wünschen.
Die Aufgabe der Mitglieder wäre es, genug Fahrzeuge günstig einzukaufen. Zum Abholen/Liefern
der Fahrzeuge wäre z.B. eine DFT wie im PD super. 

Die Autos könnte man dann z.B. bei AutoBahn kaufen, genau wie bei anderen Autohäusern.
Da das Verkaufen automatisch geschieht, bräuchte man eventuell zwei _aktive_ Mitglieder - deshalb nicht von den Spielerzahlen abhängig.
Habe eventuell noch weitere Ideen, falls der Vorschlag angenommen wird.

Mit freundlichen Grüßen
Shayan | rekz

**Comment by geramy92** [comment]
Kann man selbst tun auch ohne Fraktion. MAn würde Zivilisten nur ihrer Verdienstmöglichkeiten berauben.
