### ISSUE TITLE
Deagle Rang 3

### ISSUE THREAD

**Issue by Anonymer123** [TerraTex-Community/TerraTex-Reallife-Reloaded#302]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #....

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Ich als Rang 3er in der Grove habe keine Deagle mehr sondern eine Silenced
2. ..

**Comment by geramy92** [comment]
ist gewollt
