### ISSUE TITLE
/showhud blendet Hud nur teilweise aus

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#304]
## What type of report is this?

set the x for the correct type
- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question
## Are there other Issues that are related to this request? (If you know one)

Es wird nur die Minimap ausgeblendet

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.
## Where can we find this Issue? What are the Steps to reproduce this Bug?
1. everywhere
2. .. 
## Hinzufügbaren Zeilen als Eventueller Fix:

function showhud ()
        showPlayerHudComponent ( "ammo", false )
        showPlayerHudComponent ( "weapon", false )
        showPlayerHudComponent ( "health", false )
        showPlayerHudComponent ( "armour", false )
    showPlayerHudComponent ( "money", false )
    showPlayerHudComponent ( "area_name", false )
    showPlayerHudComponent ( "clock", false )

**Comment by geramy92** [comment]
das ist eine MTA funktion keine Terratex funktion
d.h. das ist kein bug und so einfach ist das auch nicht
(was unter anderem daran liegt, dass man nicht auslesen kann ob etwas ein oder ausgeblendet ist)

**Comment by Shariner** [comment]
Kannst du es dennoch probieren wenn du Zeit hast dies zu fixen? Das wäre sehr nice :3

:)



On Fri, Sep 9, 2016 at 1:10 PM +0200, "Geramy" <notifications@github.com<mailto:notifications@github.com>> wrote:


das ist eine MTA funktion keine Terratex funktion
d.h. das ist kein bug und so einfach ist das auch nicht
(was unter anderem daran liegt, dass man nicht auslesen kann ob etwas ein oder ausgeblendet ist)

-
