### ISSUE TITLE
Stadthalle ausloggen

### ISSUE THREAD

**Issue by HammelKen** [TerraTex-Community/TerraTex-Reallife-Reloaded#305]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------

-----------------------------------------------------------------------
1. Wenn man sich in der Stadthalle ausloggt und längere Zeit wartet wird man in eine andere Dimension teleportiert ist aber immer noch im Innenraum. D.h das man nicht mehr rausgehen kann und /suicide benutzen muss. So war es bei mir zumindest. 
2. .. 

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
> `log entries client`
> `log entries server`

**Comment by geramy92** [comment]
mh da dies etwas strange ist, kurze frage:
Was hast du gemacht bevor du in die Stadthalle gegangen bist und offline gegangen bist?

**Comment by HammelKen** [comment]
Ich bin nur in die Stadthalle gegangen und hab geguckt ob ein BIZ freigeworden ist. Dann habe ich mich ausgeloggt und ein Paar Stunden später wieder eingeloggt.

**Comment by geramy92** [comment]
mh reden wir von Dimension oder Interior ?

**Comment by HammelKen** [comment]
Ich bin mir nicht sicher was es war aber ich war noch im Stadthallen Innenraum aber es gab keine Marker mehr. Die Marker an dem Tresen haben trotzdem funktioniert der an der Tür aber nicht. Waren halt irgendwie unsichtbar
