### ISSUE TITLE
Fahrzeug vor dem man steht auf/abschließen OHNE Angabe der SLOT ID

### ISSUE THREAD

**Issue by DaBunka** [TerraTex-Community/TerraTex-Reallife-Reloaded#306]
Man sollte Fahrzeuge per Befehl auf/abschließen können ohne die SLOT ID eingeben zu müssen.

Zum Beispiel gibt man statt /lock SLOT ID einfach nur /lock ein und dann ist das Fahrzeug vor dem man steht direkt offen.

Wäre praktisch, da man sich dann nur eine Taste binden muss zum auf/abschließen von Fahrzeugen.
Und nicht 10 verschiedene Tasten mit Binds belegen, da man aktuell ja immer den SLOT mit dazu schreiben muss.

**Comment by geramy92** [comment]
Drauf klicken -> Abschließen

Ich mein es gibt realen auch keine universal schlüssel und zum anderen woher soll man zB am Haus wo mehrere stehen wissen welches. Am Ende wird noch das falsche aufgeschlossen...
