### ISSUE TITLE
Neue TLT-Apps (Ideen)

### ISSUE THREAD

**Issue by DaBunka** [TerraTex-Community/TerraTex-Reallife-Reloaded#307]
Autohäuser und normale Preise als App
Eine neue TLT-App in der die normalen Preise aller Fahrzeuge eingetragen sind (Sortiert nach Autohändler)
Eventuell sogar mit Bild zum Fahrzeug (Sofern das möglich ist)
http://www.gtavision.com/?section=content&site=122 (Bilder zu Fahrzeugen)
NICHT die aktuellen Tages-Preise, sondern nur die normalen Standard-Preise (Damit man der NEWS nicht die Arbeit mit den Rabattcars klaut. 👍 

Internet-Browser (Forum only) als App
In MTA gibt es ja die Möglichkeit, dass man Internet-Seiten ansurfen kann ingame.
Es wäre praktisch, wenn es einen Internet-Browser für das TLT geben würde mit dem man aber nur das Forum ansurfen kann.

**Comment by geramy92** [comment]
warum wir das forum nicht als app haben: zu viele fremdquellen, die alle vom user freigegeben werden müssen.

**Comment by geramy92** [comment]
bitte auch für mehrere Ideen mehrere Tickets auf machen

**Comment by DaBunka** [comment]
kenne mich da jetzt nicht wirklich aus, aber ist es nicht eig. so, dass der user nur eine domain freigeben muss? in dem fall forum.terratex.eu

oder muss jeder einzelne link einzeln freigegeben werden? :O

**Comment by geramy92** [comment]
einzelne links etc.

zB forum.terratex.eu hat sehr viele bildlinks, js links etc. deren domains andere sind. Diese müssen ebenfalls alle einzeln freigegeben werden.
