### ISSUE TITLE
Eine /sms Nummer für jede Fraktion so wie /sms 1111 für die News

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#308]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Ich denke es wäre eine Gute Idee wenn auch andere Fraktionen eine /sms Nummer hätten. Da dadurch Kontakt aufnahme mit Fraktionen stark vereinfacht wird. 

Vorteile: 
-Einfachere Ankündigung von GF.
-Evtl. einfachere Konfliktlösungen zwischen den Fraktionen.
-(Für die Taxi) Einfache Absage von Taxirufen (Ich brauch kein Taxi mehr)
-Einfache Bewerbung (bzw Auskunft über Bewerbung. Da dann der Antworten kann der Ahnung hat, bzw der Zuständig ist) (auch für  die Bewerber weil du dann nicht raussuchen musst wer der Leader ist (machen die meisten sowieso nicht))

**Comment by mirdo** [comment]
Für das PD wäre es eventuell nicht nötig da die ja /call 911 haben

**Comment by MegaEssen123** [comment]
Wäre ich dafür, das wäre ein **sehr nützliches** Feature.

Beim PD kann es allerdings trotzdem notwendig sein, da /call 911 nur für Notrufe gedacht ist.
Wenn ein Spieler eine Frage an das PD hat und diese über den Notruf stellt, so kriegt er von einem Beamten sofort Notrufmissbrauch.

Unter /service kann man die Service-Nummer dann auch anzeigen.

**Comment by geramy92** [comment]
# good luck with the spam

für sowas gibt es Leader, die eigene nummern haben

**Comment by MegaEssen123** [comment]
> _geramy92_ - good luck with the spam

Ich denke nicht, dass Spam ein wirkliches Problem darstellt.
Beim Notruf des PDs oder der Service-Nr. von der News wird ja auch kaum / nicht gespammt.

> _geramy92_ - für sowas gibt es Leader, die eigene nummern haben

'
> _mirdo_ - Einfache Bewerbung (bzw Auskunft über Bewerbung. Da dann der Antworten kann der Ahnung hat, bzw der Zuständig ist) (auch für die Bewerber weil du dann nicht raussuchen musst wer der Leader ist (machen die meisten sowieso nicht))

Eine Service-SMS für alle Fraktionen würde die Kommunikation unter den Fraktionen und zwischen Zivilist und Fraktion vereinfachen.

**Comment by geramy92** [comment]
Die Frage ist immernoch: Was muss ein ZIVILIST mit einer Fraktion klären, bei der die Ansprechpartner nicht Leader und Co-Leader sind, deren Aufgabe das ja wäre.

**Comment by geramy92** [comment]
und entschuldige Faulheit álá "machen das ja sowieso nicht" ist kein Argument, da die meisten Fraktionen sowieso bereits eine Bewerbung im Forum via Koversation oder ihren Formularen erwarten

**Comment by MegaEssen123** [comment]
> Vorteile:
-Einfachere Ankündigung von GF.
-Evtl. einfachere Konfliktlösungen zwischen den Fraktionen.
-(Für die Taxi) Einfache Absage von Taxirufen (Ich brauch kein Taxi mehr)

**Comment by MegaEssen123** [comment]
Das war nur ein Beispiel oben

**Comment by geramy92** [comment]
das einzige was ich sehe ist das letzte und das macht garantiert niemand bzw. sollte eher automatisch geschehen

**Comment by mirdo** [comment]
Es geht halt vorallem darum das alles zu vereinfachen. Weil ich auch viele Leute gehört habe das sie das Forum unübersichtlich finden und deswegen den Ansprechpartner nicht finden.

Außerdem wäre es halt zu mindest für das Taxiteam gut weil sich im Moment die Leute die dann doch keins brauchen häufen. Und bis sie die Nummer rausgesucht haben wäre der Fahrer eh schon fast da. Da wäre bspw /sms 400 praktisch

**Comment by StalkerGER** [comment]
Für Leute die dann doch kein Taxi brauchen, währe eine art Kommando nachdem man eins gerufen hat einfacher zbsp /tw (taxi wiederrufen) das der Punkt dann von der Karte verschwindet. Der Taxifahrer sollte dann die Meldung bekommen, das dass Taxi nicht mehr benötigt wird.

Was dann noch gemacht werden könnte, eine eigene /re Funktion für die /sms, die dann der /re Funktion vom Reportsystem nicht in die quere kommt. So muss man nicht immer wieder die nummer neu eingeben.

**Comment by Ceeserxx** [comment]
Man braucht doch auch nicht direkt den Ansprechpartner finden meiner meinung nach.

"Ich will in die Taxi Fraktion"
..Spieler X ist online und in der Frak
"/call 11880 - Spieler X - anruf"
"Hallo, bei wem könnte ich mich bewerben, wenn ich in die Fraktion will"
- Mirdo ist der Leader des SA:TT, ansonsten kannst du dich auch bei Bob melden.

Sache gegessen ;) Hat doch sonst auch immer so geklappt.

**Comment by geramy92** [comment]
da inzwischen sowieso mit Forum möglich (bald auch noch besser hoffentlich) nicht nötig
