### ISSUE TITLE
Truckerjob Bug beim Überfahren der Grenze

### ISSUE THREAD

**Issue by Shariner** [TerraTex-Community/TerraTex-Reallife-Reloaded#309]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

15:03
epoxi schreibt mit ingame wegen eines Bugs an. Er sei bereits 2x mit dem Tanker vom Truckerjob an der Blitzerkreuzung LV stehen geblieben und festgebuggt. Ohne Berührung zu anderen Objects. Brückenbaustelle war nicht aktiv. Blade habe es ebenfalls gesehen und auch versucht Ihn wegzurammen damit er frei kommt. 2x hats nicht funktioniert. Kaution verloren ohne ersichtlichen Grund

15:07
epoxi schreibt mir das es wieder passiert ist, diesmal nicht an der Blitzerkreuzung. Er hat mit einem Roadtrain die Straße gemieden und ist den Bahngleisen gefolgt. Auch dort blieb er ohne ersichtlichen Grund stehen. Als ich ankam hatte Ihn ein Zug quer in die Gleise gerammt. Daraufhin versucht ich in rauszuschieben, was auch funktionierte bis auf einmal zwischen meinem Sultan und dem Truck eine Explosion stattfand und beide Fahrzeuge Feuer fingen. Obwohl ich im Auto saß als mein Sultan explodierte respawnte dieser. Wurde also nicht zerstört wieso auch immer.

Ich habe absolut keine Ahnung um welche Bugs es sich hier handeln kann. Ich hab dafür keine Erklärung und kann es deshalb nur genau so beschreiben. Zudem hab ich ein Video davon (Was nur den kaputten Truck zeigt und unserer Explosion, nicht sein generelles festbuggen aufgrund von irgendwas)

https://drive.google.com/file/d/0Bxh-xkSK9t5XSGJ0RXdYbkcyc28/view?usp=sharing

**Comment by geramy92** [comment]
kein Bug, der Anhäger ist halt normalerweise hinter ihm gespawned

aber man soll ja auch nicht auf Bahnschienen fahren
