### ISSUE TITLE
Kauf von Lichtfarben funktioniert nicht

### ISSUE THREAD

**Issue by shayaaan** [TerraTex-Community/TerraTex-Reallife-Reloaded#310]
Huhu,
als ich vorhin die Lichfarbe von meinem Fahrzeug ändern wollte,
wurde mir das Geld abgezogen, die Farbe änderte sich aber nicht.
Hab das Ganze drei Mal probiert.

Hauste,
rekz

**Comment by byReaper** [comment]
Die Farbe geht manchmal erst nach einem Serverneustart, hatte ich auch schon das Problem :D
