### ISSUE TITLE
Gerüst vom Riesenrad fehlt

### ISSUE THREAD

**Issue by BliiZarD** [TerraTex-Community/TerraTex-Reallife-Reloaded#320]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
Dadurch fliegt das Innengerüst des Rades quasi in der Luft ( inkl. Gondeln ) und/oder stützt sich auf die unterste Gondel.

Das Riesenrad befindet sich direkt im Fischerjob in LS.

ID des Gerüsts sollte 6298 sein.

Danke im vorraus und ich fordere Schadensersatz von dem Mapper, der mir das Rad unfähig gemacht hat :c
Ein neues Hauptgerüst ist ja teuer :heavy_check_mark:

**Comment by geramy92** [comment]
war ceeser is behoben
