### ISSUE TITLE
Säcke des Müllmann-Jobs

### ISSUE THREAD

**Issue by BliiZarD** [TerraTex-Community/TerraTex-Reallife-Reloaded#325]
What type of report is this?
----------------------------
- [X] Feature Request / Enhancement

Um sein Fahrzeug während des Jobs nicht zu beschädigen, wie es die etwas unbegabteren Müllmänner unter uns tun ( wie ich z.B. ), würde ich es nicht schlecht finden die collision von den gespawnten Müllsäcken zu entfernen.
Es wäre unrealistisch, aber die Müllmänner im RL fahren auch nicht 1mm an den Sack um ihn aufladen zu müssen, sondern können einen gewissen Abstand einhalten.

2. Lösungsvorschlag wäre eine größere Hitbox des Markers, damit man nicht "in" den Sack direkt fahren muss.

Danke im voraus und vielleicht bin ich ja der einzig unfähige Müllmann in der großen weiten Welt von TerraTex :D

PS: Ja man kann knapp in den Marker fahren, was aber bei gewissen Gassen nicht sonderlich gut machbar ist leider :x

**Comment by geramy92** [comment]
+ setElementCollisionsEnabled ( theElement , false)
