### ISSUE TITLE
Spraydose

### ISSUE THREAD

**Issue by BliiZarD** [TerraTex-Community/TerraTex-Reallife-Reloaded#328]
What type of report is this?
----------------------------
- [x] Bug / Error Report

Auf dem Server existiert aktuell der kleine Fail, dass man sich IMMER selbst mich "ansprüht" beim benutzen der Spraydose. Die Dose sollte als Mittel zur Selbstverteidigung existieren, was so aber recht sinnlos ist, wenn man selbst auch eine kurze Zeit außer Gefecht gesetzt wird.

Vielen Dank schon mal. =)

**Comment by geramy92** [comment]
related to #95
