### ISSUE TITLE
Medic Spawnpunkt

### ISSUE THREAD

**Issue by BliiZarD** [TerraTex-Community/TerraTex-Reallife-Reloaded#329]
What type of report is this?
----------------------------
- [X] Feature Request / Enhancement

Die Medics besitzen 2 Fraktionsbasen. Ähnlich wie beim SAPD wäre es sehr angenehm, wenn die Medics via "spawnchange fraktion ls" auch in der Fraktionsbase in LS spawnen könnten.

MfG,
BliZarD

**Comment by geramy92** [comment]
dann spawnen ja alle nur noch ls..... ich mag mich erinnern aber es gab ein Grund warum wir das nicht wollten :P

**Comment by BliiZarD** [comment]
Ja, aber aktuell ist der meiste Verkehr in ls. Kann ja nicht sein das Leute sich da Ponies parken, damit sie da spawnen können :x :D

**Comment by shayaaan** [comment]
Mit den aktuellen Tankpreisen wäre mit spawnen in LS doch lieber. :D
