### ISSUE TITLE
Wenn einer am Tombupot ein Ticket kauft und nicht genug Geld dabei hat wird das allen angezeigt

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#330]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Tombupotticket kaufen und nicht genug Geld haben. Jedem anderen wird die Errorbox auch angezeigt

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
> `log entries client`
> `log entries server`

**Comment by BliiZarD** [comment]
Wollte ich auch schreiben, hatte sogar Screens gemacht, aber da war das mirdolein schneller :p

**Comment by MrHufferson** [comment]
Dieser Bug ist vorhin aufgetreten, als ich am Rookiespawn ein Ticket kaufen wollte...

**Comment by scriptcodeDE** [comment]
#311 Should be closed
