### ISSUE TITLE
/sellcar

### ISSUE THREAD

**Issue by BliiZarD** [TerraTex-Community/TerraTex-Reallife-Reloaded#332]
What type of report is this?
----------------------------
- [X] Feature Request / Enhancement

Man sollte /sellcar in sofern erweitern, sodass man dort angezeigt bekommt, ob das Angebot überhaupt übermittelt wurde und ebenfalls, ob dieses danach angenommen wurde. Bestes Beispiel wäre hierfür der Mechanikerjob.
/sellcar [NAME] [SLOT] [BETRAG]
"Sie haben [NAME] erfolgreich Ihren [FAHRZEUG] für [BETRAG] angeboten."
"[NAME] hat Ihr Angebot aktzeptiert."
(Oder so ähnlich - bin gerade nicht sonderlich kreativ)

Würde Misverständnisse und Verwirrungen beheben.

Zusätzlich sollte das GUI des Fahrzeuges um die Spalte "Betrag" erweitert werden, da man sonst nur den Namen angeben kann und der Parameter des Betrages fehlen würde.

Danke im Voraus.

**Comment by geramy92** [comment]
im gui ist nur /givecar nicht sellcar

**Comment by BliiZarD** [comment]
Wenn man aber im GUI einen Namen eingibt kommt die Errormeldung von Sellcar, dass ein Parameter fehlt.

**Comment by geramy92** [comment]
mh dann habe ich vergessen das umzustellen
