### ISSUE TITLE
Nagelbänder funktionieren nicht.

### ISSUE THREAD

**Issue by MrHufferson** [TerraTex-Community/TerraTex-Reallife-Reloaded#334]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. /cspike -> Das Nagelband erscheint
2. Ein Auto, (Motorrad auch getestet) fährt über das Nagelband und die Reifen gehen nicht kaputt.

**Comment by geramy92** [comment]
Fehlermeldungen Client:

> [2016-09-18 00:15:21] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]
> [2016-09-18 00:15:27] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]  [DUP x242]
> [2016-09-18 00:15:27] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]
> [2016-09-18 00:15:33] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]  [DUP x208]
> [2016-09-18 00:15:35] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]
> [2016-09-18 00:15:41] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]  [DUP x669]
> [2016-09-18 00:15:41] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]
> [2016-09-18 00:15:47] WARNING: terratex_reallife\ENVIRO\fraktionen\lspd\spikes\spikes_client.lua:32: Bad argument @ 'isLineOfSightClear' [Expected vector3 at argument 4, got nil]  [DUP x225]

**Comment by scriptcodeDE** [comment]
Warum funktioniert eigentlich alles einwandfrei auf meinem Server und dann nie auf dem Live-Server? xD

**Comment by geramy92** [comment]
tja
