### ISSUE TITLE
Tankstellen Vorschlag

### ISSUE THREAD

**Issue by Unitatoe** [TerraTex-Community/TerraTex-Reallife-Reloaded#335]
What type of report is this?
----------------------------
set the x for the correct type

- [] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
Ich habe mir mal Gedanken gemacht wie man das Tankstellen Konzept überarbeiten könnte und mir ist dazu eine Ideen eingefallen, also wollte ich mal fragen was ihr davon halten würdet. 
Man könnte es ja so machen das an unterschiedlichen Tankstellen auch unterschiedliche Preise angeboten werden. So kann man nachschauen, wie es ja auch ungefähr im RL abläuft, wo es gerade am günstigsten Angeboten wird und sich somit entscheiden.

**Comment by BliiZarD** [comment]
Dann müssten das aber mind. 2 verschiedene Tankstellenketten sein, demnach 2 BIZ und viel Aufwand für einen eventuellen Sparfaktor von 50$ pro Tankfüllung, was nun nicht die Welt ist :P

Aber mal sehen was Geramy und Günni dazu sagen :x

**Comment by geramy92** [comment]
2. Biz und so eher nicht, aber man könnte generell das Tanksystem umbauen, dass jede Tanke eigene Preise (die natürlich genauso generiert werden wie der jetzige) generiert.

Zusätzlich:
/fraktank [Prozent] - Beim Tanken mit einem Fraktionsfahrzeug werden [Prozent]% von der Frakkasse übernommen.

**Comment by geramy92** [comment]
Ticket in entsprechende Teiltickets geteilt
