### ISSUE TITLE
Homepages der Fraktionen

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#338]
Fraktionen nicht mehr bei externen Anbietern hosten sondern auf TerraTex-Subdomains (sapd.terratex.eu).

Login möglich mit Ingame-Passwort (für Mitglieder der Fraktion mit Leader-Rechten) (Automatisch aus der TerraTex-DB)
Kleines Art CMS
Mitglieder-Reiter, der aus der DB gelesen wird

Würde ich mich auch zu bereit erklären die Arbeit zu übernehmen.

**Comment by scriptcodeDE** [comment]
P.S.: Datenbankzugriff nur über mysqli

**Comment by byReaper** [comment]
Wäre es nicht besser das in das kommende UCP zu integrieren? (falls Geramy das noch vor hat)

**Comment by geramy92** [comment]
da github für das script ist, wäre das hier im forum besser aufgehoben ;-)
