### ISSUE TITLE
Taxifraktion spawnt ohne Pfefferspray

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#341]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Im Vergleich zur Medic hat die Taxi im Moment keine Möglichkeit das Pfefferspray zu bekommen

**Comment by BliiZarD** [comment]
In meinen Augen bringt das Spray im aktuellen Zustand eh nichts, außer das man Leute im Umkreis von 20-30m mobbt.
Man selbst kann sich ja nicht verteidigen, da man immer selber getroffen wird.

Bis zum vollständigen Fix von [https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/issues/95](#95).

Fraglich ob es bis dahin dem Server hilft :P

Soll aber nicht so negativ klingen, jedoch sollte es lieber vom Server komplett runter, anstatt es noch mehr Menschen zu geben bis zum fix :x

**Comment by mirdo** [comment]
Es geht ja generell darum das es bei uns nicht funktioniert. In welchem Maße das Spray im Moment Sinn macht ist da ja unerheblich

**Comment by mirdo** [comment]
Wir brauchen es IM MOMENT deswegen auch nciht dringend. Aber trotzdem war es Zeit dies zu melden. Außerdem wurde laut letztem Update das Problem ja eingedämmt. Zu mindest laut Patchnotes

**Comment by geramy92** [comment]
die beschreibung stimmt sowieso nicht
Ihr bekommt genauso wie die Medics das Spray. Aber eben nur wenn ihr komplett respawned. In Anderen Worten: wenn ihr sterbt.

Ich hab das jetzt auch auf /duty gebindet.

Zusätzlich /duty resetet die Spielerwaffen.
