### ISSUE TITLE
(Neue) Autohändler

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#342]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request? (If you know one)
--------------------------------------------------------------------------
- #321 
- #344 

https://docs.google.com/spreadsheets/d/1q8yJPQ5DwdQrrrN3D5cZwpdOrH2Mcllz1eQox7bHOCs/edit#gid=325070682
Anbei auf Tabellenblatt 2 der Aufbau der neuen Autohäuser (mit alten Preisen)
und auf 4 Welche Auto´s wohin wechseln  
Script wird von MennoMax gemacht und ist schon sehr bald fertig

Dafür noch zwei Fragen:
Soll der Stuntplane noch weg? Momentan würde ich den Stuntplane beim ehem Premium stehen lassen weil der Platz sonst eh leer wäre. Wenn der Stuntplane noch zum Flughändler soll können wir dann den Yosemite nehmen und auf seinen Platz stellen?

Desweiteren haben wir die Preise jetzt so gelassen wie sie sind. Die neuen Autos bekommen erstmal einen Platzhalter im Script. 
Da bröchten wir noch Rückmeldung wie wir das machen sollen und was mit dem Multiplikator am unteren Ende des Scripts passieren soll.

MFG

**Comment by geramy92** [comment]
Ein Ticket reicht ;-)

**Comment by mirdo** [comment]
Ja entschuldige.  
Dieser Thread bleibt jetzt auch.  Aber es hat sich halt viel geändert und wir bröchten relativ bald ne Antwort  deswegen war ich mal so frech :P
Weil es momentan so aussieht als könnte es von unserer Seite aus die Woche noch gemerged werden.
