### ISSUE TITLE
Ingame Voice-Chat

### ISSUE THREAD

**Issue by scriptcodeDE** [TerraTex-Community/TerraTex-Reallife-Reloaded#343]
Ingame Voice-Chat mit folgenden Funktionen:
- mit Spielern in der Nähe reden
- mit Spielern über das Handy reden
- mit Teammitgliedern über ein Funkgerät reden
- mit Beamten über ein Funkgerät reden
- Megafon

Folgendes müsste geprüft werden:
- Ist die Sprachqualität akzeptabel?

Kann von mir ab nächster Woche implementiert werden

**Comment by geramy92** [comment]
darüber habe ich auch schon nachgedacht. Aber bevor ich da zusage, möchte ich eher über ein sinnvolles Konzept nachdenken. Ich meine es sind so viele Kanäle die hier oft benutzt werden und Teamspeak, dass es am ende nur noch ein durcheinander wird. Daher wäre eher zu überlegen, nur Teilweise solch funktion zu unterstützen: z.B. ein /voicecall für das Handy oder ähnliches.

**Comment by scriptcodeDE** [comment]
Würde ggf. halt viel mehr RP reinbringen. Desweiteren sollte es ne Funktion zum muten von anderen Spielern Ingame geben. (Damit man selber ein wenig das Chaos abstellen könnte.

**Comment by scriptcodeDE** [comment]
Außerdem könnte es DAS Feature sein, was den Server von anderen unterscheidet ;)

**Comment by geramy92** [comment]
Ändert immernoch nichts an meiner Aussage: Ich halte ein einfügen für überall und alle Kanäle für ein zugroßes durcheinander. (auch wenn man andere Muten kann). Zumal sowieso viele ihren Ingamesound muten.

Ich bin da eher für gezielte features dafür, wie oben genannt Voice calls.

Sprachqualität hängt übrigens mit der Serverconfig zusammen, weshalb wir als open source script auch berücksichtigen müssten, dass auf anderen Servern der Voicechat deaktiviert wird.

**Comment by scriptcodeDE** [comment]
Für mich machts eigentlich nur Sinn, wenn man das komplett durchzieht oder es lässt. Die Leute müssen ja auch nicht im TS sein, wenn sie den Voicechat auf dem Server benutzen.

**Comment by StalkerGER** [comment]
Gibts denn ne Beschränkung, das man erst ab X (25-50) Spielstunden den benutzen kann?

Kann mir sonst schon richtig vorstellen, wie der dann die ganze Zeit missbraucht wird von neuankömmlingen.

**Comment by scriptcodeDE** [comment]
Inwiefern? Es gibt ja keine globale Kommunikation zwischen allen Spielern. Desweiteren kann man ja den Spieler muten, wenn er einen nervt :D

**Comment by geramy92** [comment]
Tja also mr @scriptcodeDE wenn du ab sofort die gameplay entscheidungen so einfach machen willst: dann gar nicht

**Comment by scriptcodeDE** [comment]
Ja ist kein Problem, ich finde das macht sonst keinen Sinn, wenn man z.B. ingame telefonieren kann aber sonst nichts ^^

**Comment by geramy92** [comment]
es geht nicht darum das, dass das die einzige sache sein soll, sondern darum, dass ich ein Konzept haben will und kein "wir machen mal kurz alle chats zu voice chats damit alles den bach runter geht"

**Comment by scriptcodeDE** [comment]
Die alten Text-Chats kann man ja nach wie vor nutzen. Was fehlt dir an meinen Vorschlägen an Infos, ohne die du direkt zum schluss kommst "damit alles den bach runter geht"

**Comment by geramy92** [comment]
das habe ich jetzt ungefähr schon gefühlte 10 mal erläutert wenn dus nicht
verstehst kann ich langsam auch nichts mehr dafür

2016-09-22 19:33 GMT+02:00 scriptcodeDE <notifications@github.com>:

**Comment by Ceeserxx** [comment]
Also @scriptcodeDE , es soll ein lokaler voicechat sein? Im Umkreis von vllt 25-50 metern?

**Comment by HammelKen** [comment]
Ich glaube er will es so umsetzen wie das Arma 3 Task Force Radio.  Die Idee kommt dem nämlich schon sehr nahe und Funktioniert halt über TS und nicht über inGame Voicechat. Alle Spieler die Online sind werden sobald sie Online kommen in einen Channel gezogen und gemuted. Jenachdem wie nah ein Spieler dir kommt wird er Automatisch für den, der in der nähe ist entmuted und man halt reden. Für genauere Erläuterungen Videos angucken. Allerdings weiß ich nicht ob es so was in der Art für MTA gibt oder sowas in MTA möglich ist.

**Comment by Ceeserxx** [comment]
Wäre ja auch nicht schlecht, aber ich finde, dass man es erst aktivieren sollte mit /vc oder sowas oder quasi push to talk einbauen, wenn das denn ginge.

Oder wie ich es richtig gut finden würde:
/vc, /startvc o.ä. zum Starten vom Voicechat. Es kommt jede minute, alle 2 oder 3 min einmal die Meldung, dass der Viodechat aktiv ist, falls es kein Push to Talk geben kann/gibt.
Den Voicechat hören können nur die Spieler, die ihn auch selber gestartet haben. Reden ebenfalls.
Neben dem Namen des Spielers, der Voicechat aktiviert hat könnte vielleicht ein Mikrofon Symbol sein, das alle sehen können, um erkennen zu können mit wem man reden kann.
Der Viocechat sollte über 25 bis max. 50 Meter gehen können.
Eine Anzeige, wer im "Empfangs-Radius" gerade redet am Bildschirmrand wäre schön, sofern möglich.
/svc, /stopvc o.ä. sollten den Voicechat wieder Stoppen, ebenso wie /afk, vielleicht auch sterben, da man dann nichtmehr reden kann.

**Comment by scriptcodeDE** [comment]
Ok, Geramy ich schreibe demnächst ein detaillierteren Text wie ich mir das vorgestellt hatte.

**Comment by scriptcodeDE** [comment]
@Ceeserxx Ich muss selber erstmal rausfinden wie MTA das ganze ausliefert. (Push-to-Talk denke ich aber) Das mit der abnehmenden Lautstärke wäre cool, jedoch kann ich MTA leider nicht sagen, wie laut er einzelne Spieler drehen soll :D

**Comment by leoncon99** [comment]
Das ist eine echt gute Idee. So wie bei Arma 3 Altis Life (Jetzt nur als Beispiel)
