### ISSUE TITLE
Es spawnen keine Marker mehr beim Mülljob

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#357]
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. Wenn man in einen Müllwagen einsteigt kommen keinerlei Marker. Auch kein Abgabe Marker

**Comment by geramy92** [comment]
da hat wohl jemand was kaputt gemacht :P Ich bräuchte bitte einmal die clientside logs
