### ISSUE TITLE
Tanken haben inviduelle Preise

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#358]
Teil von #335 

-> Tankstellen haben alle eigene generierte Preise

**Comment by mirdo** [comment]
Passend hierzu einen Befehl für die News damit die über die Preise berichten können? Alternativ eine TLT App?

**Comment by geramy92** [comment]
maximal als extra Featurerequest
ein Befehl macht da aber keinen Sinn da es ~20 Tankstellen sind. Das in eine chatbox zu basteln ist nur ätzend.

Über TLT habe ich auch schon nachgedacht, wie eine Tabelle aller Tankstellen und Preise, die Sortierbar ist nach Entfernung oder Preis oder ....
