### ISSUE TITLE
/inviteCheck [Name] bzw /check [Name] für Fraktionen

### ISSUE THREAD

**Issue by mirdo** [TerraTex-Community/TerraTex-Reallife-Reloaded#360]
What type of report is this?
----------------------------
set the x for the correct type

- [ ] Bug / Error Report
- [x] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Ein Befehl der /invite entweder komplett ersetzt oder als Zusatz dazu kommt. /inviteCheck (o.ä.) gibt dem Leader oder Person mit Rechten aus ob die Person die Invited werden soll momentan gesucht wird, Drogen, Materialien oder Waffen dabei hat. Danach muss der Leader (ähnlich wie beim Durchstellen bei 11880) mit Ja bzw. Nein bestätigen ob der Invite durch geführt wird oder nicht.

Zum Verhindern von Missbrauch sollte der "Durchsuchte Spieler" auch eine Meldung bekommen.

Alternativ:
/check [name] zum Kontrollieren von Fraktionsmitgliedern also im Endeffekt so wie der Befehl vom PD

**Comment by geramy92** [comment]
Ich verstehe ehrlich gesagt, den Sinn nicht wirklich

**Comment by mirdo** [comment]
für Neutrale Fraktionen. Damit wir halt selber nach schauen können ob die Member gegen die Regeln verstoßen und nicht auf das PD angewiesen sind.

**Comment by mirdo** [comment]
Vorhin klang das in meinem Kopf noch sinnvoller

**Comment by geramy92** [comment]
dann eher, dass man frisk abändert zu einem Befehl mit accept, dafür von allen Nutzbar
und für die Beamten sowas wie ein /forcefrisk

**Comment by geramy92** [comment]
umgeswitcht zu einer anderen Lösung, die funktionieren sollte dafür
