### ISSUE TITLE
TerraTex Insel(n)

### ISSUE THREAD

**Issue by shayaaan** [TerraTex-Community/TerraTex-Reallife-Reloaded#369]
Hey Leute,

mir ist vor Kurzem aufgefallen, dass kein Reallifeserver Inseln besitzt.
Auf diesen Inseln könnte es spezielle 'Events' geben, welche User auf die Inseln
lockt. Ebenso könnten die Inseln auch neue User zum reinschnuppern anziehen.

Es sollte einen Hafen sowie einen (KLEINEN!!!) Flughafen geben, damit die User anreisen können.
Die Inseln sorgen dafür, dass 1.) User mehr Flugzeuge und Boote kaufen sowie 2.) mehr Unternehmen gegründet werden (Reedereien/Airlines). 

Sofern diese Idee auch positive angenommen wird, würde ich mich daran machen, weiteres auszuarbeiten. 
Hauste,
rekz

**Comment by mirdo** [comment]
Die Idee an sich find ich gut. Probleme sind nur das man dann komplett neue flächen mappen müssten die 1. sehr groß werden von der Datei 2. Viel Arbeit sind und 3. soweit ich weiß, schwer sind das sie wirklich gut aussehen weil es ja keine wirklichen tools gibt um zu "geoformen" 

Desweiteren ist die Sache das die SA Map bereits sehr groß ist und wir die bisher nicht mal annähernd auslasten. 
Meiner Meinung nach sollte man sich eher überlegen den Rest der Map einzubinden anstatt eine ganz neue zu machen.

**Comment by shayaaan** [comment]
Viel Speicher - ja. Viel Arbeit - ja.
Aber es lohnt sich. Wir wären weltweit der erste
Server - das zieht natürlich Spieler aus der ganzen Welt
an. Die Map ist nicht aktuell nicht ausgelastet, ich weiß. Dennoch:
Du kannst eine Insel nicht mit der restlichen Map vergleichen. Sofern man
genügend Aktivitäten auf der Insel anbietet, welche User auf die Insel locken,
werden wir diese Insel auslasten. Auch für Newsevents kann die Insel genutzt werden.

Für das anstehende Adventsevent wäre es doch auch ganz cool?
Das coole an der Insel ist, dass man eben nicht einfach so rüberkommt.
Man ist angewiesen auf weitere Unternehmen - oder man kauft sich eben selber was.
Das ist, meiner Meinung nach, extrem realistisch.

**Comment by geramy92** [comment]
Ich sags mal so: Ich bettel seit Gründung von TT jeden Mapper an ein paar zu machen, vllt auch paar mit besonderen Häusern etc.   

was ich bis jetzt bekommen habe: Nichts :'(

**Comment by shayaaan** [comment]
evtl. eine große Hauptinsel und dann noch einpaar kleinere. Vielleicht könnte man aus den kleineren Inseln ja Prestigeobjekte machen? Wichtig ist halt, dass die Hauptinsel eine kleine Landebahn hat. Die kleineren Inseln könnte man ja mit Helis anfliegen. Außerdem müssten die Inseln einzigartige Aktivitäten beinhalten, damit User die Insel betreten. Wie auch schon erwähnt könnte auch die Newsfraktion die Inseln nutzen. 

Falls jemand genug Kenntnisse dafür hat: 
Ich bezahle diejenige Person, welche bereit ist, die Inselgruppen zu mappen.

**Comment by geramy92** [comment]
Da es hier eher eine Diskussion ist, schließe ich das mal. Sollte es je eine gemappte Insel geben, kann man mit der angehängten Datei ein eigenes Ticket/Pullrequest öffnen.
