### ISSUE TITLE
Bizbank Pacht

### ISSUE THREAD

**Issue by Vanity1206** [TerraTex-Community/TerraTex-Reallife-Reloaded#376]
===
[Deutsche Version]   
   
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Neues Biz kaufen 
2. In den Maker laufen um zu sehen bis wann die Pacht bezahlt ist
3. "Die Pacht deines Biz ist noch bezahlt bis: 1.1.1970" steht bei meinem

**Comment by geramy92** [comment]
done ;-)
