### ISSUE TITLE
Status sounds

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#377]
- [ ] Fehler / Bug Meldung
- [x] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Ich fände es gut, wenn man den Herzklopf und Hunger Sound an und aus schalten könnte per Befehl, da diese u.a. stören können.

**Comment by Johann0215** [comment]
//push

**Comment by geramy92** [comment]
siehe F3
