### ISSUE TITLE
Fahrzeug Verkauf an Server %-Satz erhöhen

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#394]
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.
- Derzeit werden bei einem Verkauf eines Fahrzeuges an den Server nur 25% des Kaufpreises erstattet. Die 25% auf 50%-75% erhöhen.

**Comment by LightningKirito** [comment]
Dies würde zu einem "Geldsegen" beitragen. Ich lass mir etwas überlegen.

**Comment by LightningKirito** [comment]
Bei Verkauf eines Fahrzeuges an den werden nun 55%, statt 25% erstattet.
