### ISSUE TITLE
Zerstörung eines Fahrzeuges %-Satz erhöhen (Versicherung)

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#395]
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.
- Wenn man eine Autoversicherung abschließt, sollte bei Zerstörung eines Fahrzeuges 75% des Einkaufpreis erstattet werden. Derzeit sind es nur 25%.

**Comment by LightningKirito** [comment]
Ich lass es mir durch den Kopf gehen. Finde, dass 75% zu viel sind.

**Comment by Johann0215** [comment]
Die Versicherung kostet 150k und je PayDay noch einen kleinen Betrag. 75% hat man früher bei  Premium zurück bekommen. Dies sollte nun auf die Versicherung geändert werden.

**Comment by LightningKirito** [comment]
Eine richtige Versicherung übernimmt bei einem Totalschaden auch nicht wirklich so viel..
Wären 50% auch in Ordnung, maximal 55%? Anderes könnte zu einem Geldsegen heranwachsen.

**Comment by LightningKirito** [comment]
Bei Zerstörung eines Fahrzeuges werden nun 55%, statt 25% erstattet.
