### ISSUE TITLE
Spawnsystem 

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#396]
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Spawnsystem so abändern, das man auswählen kann, ob man an seiner letzten Position oder im Haus etc. spawnen möchte nach einem Serverrestart. (Derzeit spawnt man immer an dem Punkt, wo man sich ausgeloggt hat.)

**Comment by LightningKirito** [comment]
Ist dies nur bei uns Admins so oder bei jedem Spieler?

**Comment by Johann0215** [comment]
Bei jedem Spieler.

**Comment by LightningKirito** [comment]
Ich schau mal nach, woran es liegt.

**Comment by LightningKirito** [comment]
Kein Fehler - Realismus gewährleisten.
