### ISSUE TITLE
Knast - Kaution herabsetzen

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#397]
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Die Kaution ist viel zu hoch. Preise sollten angepasst werden.
-> Du sitzt 17 Minuten im Knast. Kaution: $ 107,500.00

**Comment by LightningKirito** [comment]
Kommt mir eher als ein Bug vor, statt einer Überarbeitung des Kautionssystems.
Ich schau mal nach, eventuell ist die Rechnung etwas falsch.

**Comment by LightningKirito** [comment]
Ist weder ein Bug, noch wird es überarbeitet. Die Berechnung zeigt, dass umso höher die Jailtime, desto höher die Kaution ist. Gehst du mit der Jailtime runter (sprich, du sitzt schon etwas länger), geht auch die Kaution herab. Die Kaution, welche du oben niedergeschrieben hast, ist die Restkaution, welche noch übrig ist. Die Anfangskaution geht von deinem Status als Gesuchter (z.B. Krimineller, Schwerkrimineller, ...) heraus. Zudem gibt es den Job "Anwalt", welcher dich günstiger aus dem Gefängnis holen kann, bedeutet Arbeit für Spieler.

~closed
