### ISSUE TITLE
GF-Gebiete Drogen einkommen senken

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#405]
- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Einkommen (Drogen) von GF-Gebieten runtersetzen. 
Grund: Binnen eines Tages kann ein Volumen von 12k Drogen erhalten werden.

**Comment by LightningKirito** [comment]
Dies kommt halt vor, wenn man zu 75% der Gebiete besitzt. Normalerweise bekriegt man sich auch alle 2 Stunden darum..
