### ISSUE TITLE
Taxi Tor geht nicht

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#406]
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Taxi Fraktion gehen
2. Versuchen das Tor zu öffnen (mit /mv)
`

**Comment by LightningKirito** [comment]
Fehler nach nächsten GMX behoben, sofern Datei auf Server hochgeladen.
