### ISSUE TITLE
Interiormarker-Datenbank?

### ISSUE THREAD

**Issue by BritishEye** [TerraTex-Community/TerraTex-Reallife-Reloaded#41]
Wo sind die Interior-Marker? Muss man die selber in der Datenbank einfügen oder hast du es vergessen sie hochzuladen? :package: 
Liebe Grüße,
BritishEye

**Comment by geramy92** [comment]
man sollte natürlich nach dem Updaten auch entsprechende SQLs importieren siehe 
https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/blob/master/terratex_reallife/SQLS/update.1.0.0.sql

und für 1.1.0 auch noch
https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/blob/master/terratex_reallife/SQLS/update.1.1.0.sql
