### ISSUE TITLE
Spielstundenanzahl temporär hochsetzen und weiteres zum MTA Server

### ISSUE THREAD

**Issue by TheJonas1** [TerraTex-Community/TerraTex-Reallife-Reloaded#410]
Was für eine Art von Problem ist das?
_Der MTA-Server hat am Tag schätzungsweise an die 10 Leute Durchlauf. Daher stellt sich die Frage, warum die User den Server so schnell wieder verlassen. Ich fände es daher cool den "Rookie-Status" temporär auszusetzen, um die Möglichkeiten des Roleplays zu erhöhen. Mein Vorschlag wäre hierbei sofort beim "Joinen" die 25 Stunden zu erhalten auch, wenn man hier durch die steuerlichen Vorteile verliert. Desweiteren plädiere ich alle "inaktiven Fraktionen" zu schließen, um PD, LLS und Grove aufzufüllen, um mehr Spielspaß zu garantieren. Regeln sollte man erst aufstellen wenn man wieder eine "konstante" Spieleranzahl hat._ 
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [X] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

**Comment by LightningKirito** [comment]
Manche Fraktionen wurden jetzt geschlossen. Dies wurde angenommen.

Die Spielstunden werden jedoch nicht hochgesetzt. Denn der Rookie-Status ist dafür da, Neulinge innerhalb dieser Zeit vor jeglichen Schaden anderer User zu schützen. So wird auch das DM in jeglicher Hinsicht reduziert.
