### ISSUE TITLE
GT  überarbeiten

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#412]
Was für eine Art von Problem ist das?

Der GT kann Offduty und ohne "Gegner" gestartet werden.
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. GT starten
2. .. 

Sende bitte alle nötigen Log-Files / Log-Einträge mit? (Client- und Serverseitig) 
----------------------------------------------------------------------------------
> `log entries client  Pfad: [Your MTA-Installation]/MTA/logs/clientscript.log`   
> `log entries server`

**Comment by LightningKirito** [comment]
Geldtransporter wurde mit dem neuen Changelog "community.reloaded-1.0.3b" überarbeitet.

/close
