### ISSUE TITLE
Wenn Autos Hochgehen kein Geld (mit/ohne Versicherung)

### ISSUE THREAD

**Issue by Kacper37** [TerraTex-Community/TerraTex-Reallife-Reloaded#418]
[English - Version (für eine deutsche Version siehe unten)]   

   
What type of report is this?
----------------------------
set the x for the correct type

- [x] Bug / Error Report
- [ ] Feature Request / Enhancement
- [ ] Refactoring / Removerequest
- [ ] Question

Are there other Issues that are related to this request?
--------------------------------------------------------
- #....

Delete the rest of the template if you are writting a Feature Request or have simply a question and describe it on your own. In Case of Bug Report or Enhancement use it.

Where can we find this Issue? What are the Steps to reproduce this Bug?
-----------------------------------------------------------------------
1. [edit here]
2. .. 

Are there any Log entries that are related to this Issue? (Client AND Server side) 
----------------------------------------------------------------------------------
> `log entries client  Path: [Your MTA-Installation]/MTA/logs/clientscript.log`   
> `log entries server`

    
===
[Deutsche Version]   
   
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. [edit here]
2. .. 

Sende bitte alle nötigen Log-Files / Log-Einträge mit? (Client- und Serverseitig) 
----------------------------------------------------------------------------------
> `log entries client  Pfad: [Your MTA-Installation]/MTA/logs/clientscript.log`   
> `log entries server`

**Comment by LightningKirito** [comment]
Kann den Fehler nicht reproduzieren. Habe stets das Versicherungsgeld, wie im Script vorhanden ist, erhalten. Bitte einmal die Errors aus der Console und dem clientscript.log (siehe wie bei Farmer-Job Fehler) posten.

**Comment by geramy92** [comment]
Es gibt hier kein Clientscript !?
Wäre gut mal eine ungefähre Uhrzeit und Datum zu haben, damit ich die Serverlogs filtern kann :-)

**Comment by Johann0215** [comment]
20.01.2020 ca. 17:28 Uhr

-> Johann, Slot 37, Clover

**Comment by Kacper37** [comment]
> Kann den Fehler nicht reproduzieren. Habe stets das Versicherungsgeld, wie im Script vorhanden ist, erhalten. Bitte einmal die Errors aus der Console und dem clientscript.log (siehe wie bei Farmer-Job Fehler) posten.

Naja ich habe es so hinbekommen, dass ich mir nen clover gekauft habe und den einmal direkt zerballert habe, der ist dann komischer Weise einfach respawnt, habe dann nochmal drauf geschossen und schwups stand im chat Fahrzeug Slot ... wurde zerstört, habe aber kein Geld bekommen und zu dem kam keine Nachricht, dass ich iwas an geld bekommen haben soll.

**Comment by geramy92** [comment]
das strange: ich hab ne fehlermeldung gefunden.... die macht nur absolut keinen sinn

**Comment by geramy92** [comment]
Ist dieser Text gekommen? 
"Ihr Fahrzeug im Slot %s wurde zerstört"

**Comment by geramy92** [comment]
Ich bin mir sicher, dass es einen größeren Bug im zusammenhang mit Fahrzeugkauf gibt, ich weiß allerdings noch nicht wo und warum
