### ISSUE TITLE
/rules funktioniert nicht

### ISSUE THREAD

**Issue by TheJonas1** [TerraTex-Community/TerraTex-Reallife-Reloaded#437]
Was für eine Art von Problem ist das?
Der command "/rules" funktioniert nicht. Wäre vielleicht besonders hilfreich wenn man diesen entfernt oder mit der Funktion verknüpft, dass das GUI mit den Regeln aufgeht.
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
Nein

**Comment by geramy92** [comment]
Der Text stammt noch aus einer Zeit als es das heutige F1 noch nicht gab :P Es gibt schlicht kein F1, habe den Text daher angepasst.
