### ISSUE TITLE
Wetter schaltet zeitgleich mit neuer Meldung um.

### ISSUE THREAD

**Issue by Masei97** [TerraTex-Community/TerraTex-Reallife-Reloaded#446]
Was für eine Art von Problem ist das?
Das Wetter schlägt, sobald die News eine neue Wettermeldung bekommen, sofort auf irgendetwas um und ändert sich nach den geplanten 3 Minuten auf das Angesagte

Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Wettermeldung geht bei News ein
2. Wetter ändert sich auf irgendetwas
3. Nach 3 Minuten: Wetter wird geändert, wie es in der Meldung steht

**Comment by Johann0215** [comment]
@Masei97 
War zum Zeitpunkt der Wetter Änderung zufällig [TTeam]Johann online oder 15 Minuten davor?

**Comment by Masei97** [comment]
Bin mir nicht sicher, ist aber vor und nach der Meldung schon öfter passiert. Ich werds beobachten.

**Comment by Johann0215** [comment]
Da war dann wohl eine Wetterfee am Werk.
//close
