### ISSUE TITLE
Tankstelle funktioniert nicht (Sweeper)

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#447]
Was für eine Art von Problem ist das?
Man kann die Sweeper vom Job nicht betanken.
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- Nein

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Sweeper Job starten.
2. Versuchen zu tanken.
3. Der Sweeper fährt einfach durch den Tankmarker durch.

**Comment by geramy92** [comment]
muss man sweeper überhaupt tanken !?

**Comment by Johann0215** [comment]
Meines Wissen nach müssen alle Jobvehicle getankt werden und da es nervig ist ständig nen neues Sweeper (Bus, usw.) zu nehmen fährt man halt eben an die Tanke.

**Comment by geramy92** [comment]
die Frage war eher: geht das Benzin vom Sweeper überhaupt runter... weil ggf. habe ich vergessen damals, einzustellen, das man den Sweeper tanken muss

sonst fällt mir nämlich kein Grund ein, warum es nicht gehen sollte
und eine Fehlermeldung gibbet nicht

**Comment by geramy92** [comment]
Trat das nur das eine mal auf, oder konntest du das an mehren Tagen nachstellen?
