### ISSUE TITLE
Arena - GunGame nach tod weiter schießen & laufen

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#451]
**Was für eine Art von Problem ist das?**
--------------------------------------------------------------------------

Wenn man einen Spieler in der GG-Halle tötet kann dieser für ca. 5 sec. noch in eine Richtung laufen und weiter schießen, der "Skin" liegt also nicht tod auf dem Boden.

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
--------------------------------------------------------------------------
- Nein

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Arena betreten (GunGame)
2. Spieler töten
3. Spieler kann nach dem Tod noch weiter laufen und schießen (5 sec.)

**Comment by geramy92** [comment]
Ich weiß ehrlich gesagt nicht, wie ich das beheben soll.... Es funktioniert eigentlich alles wie es soll und der Code ist korrekt... es kommt mir wie ein komplett verrückter MTA:SA Bug vor... kp wie man das beheben soll... vllt. fällt mir auch ein workaround ein...

**Comment by LightningKirito** [comment]
Der Fehler tritt auch bei Gangfigfhts auf, wo ich mal gegen Johann gekämpft hatte.

**Comment by geramy92** [comment]
ist gelöst mit #520
