### ISSUE TITLE
/fmanage funktioniert nur teilweise

### ISSUE THREAD

**Issue by TheJonas1** [TerraTex-Community/TerraTex-Reallife-Reloaded#456]
Was für eine Art von Problem ist das?
Seit dem neuen Fahrzeughändler Update. Funktioniert zwar das UI für /fmanage, aber die Reiter werde nicht mehr geladen. Es steht nur da "Inhalt wird geladen, bitte warten..."
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
Nein

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
Nein

Sende bitte alle nötigen Log-Files / Log-Einträge mit? (Client- und Serverseitig) 
In den logs ist nichts zu sehen. Wenn doch kann dich diese noch anhängen falls nötig
![mta-screen_2020-01-20_18-00-27](https://user-images.githubusercontent.com/58854711/72744893-c4c7d400-3bae-11ea-8e34-e7940a5ba1a2.png)

> `log entries client  Pfad: [Your MTA-Installation]/MTA/logs/clientscript.log`   
> `log entries server`

**Comment by Johann0215** [comment]
Der PD-PC hat das selbe Problem.
