### ISSUE TITLE
Rabattcars - Icon Newsbase

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#460]
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Newsbase gehen
2. In das Icon für Rabattcars laufen
3. #SPAM

Wenn man in das Rabattcars Icon geht, kommt gefühlt 10x die Info der Rabattcars in den Chat.

**Comment by geramy92** [comment]
fun fact: je häufiger das autohaus besucht wurde, um so häufiger kommt die nachricht :D
