### ISSUE TITLE
Rabbattcars Marker wird beim durchlaufen 9x aktiviert

### ISSUE THREAD

**Issue by Masei97** [TerraTex-Community/TerraTex-Reallife-Reloaded#461]
Was für eine Art von Problem ist das?
Der Rabattcars-Marker in der Newsbase zeigt beim Durchlaufen die gleiche Nachricht 9 mal an.
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Rabattcars-Marker durchlaufen ==> Nachricht erscheint sehr oft.

Sende bitte alle nötigen Log-Files / Log-Einträge mit? (Client- und Serverseitig) 
----------------------------------------------------------------------------------
> Keine relevanten Aufzeichnungen vorhanden.

**Comment by Johann0215** [comment]
doppelt siehe: https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/issues/460
