### ISSUE TITLE
PD - hinzufügen eines Wantedgrund

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#472]
Was für eine Art von Problem ist das?
----------------------------
Setze das x an die richtige Stelle

- [ ] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [x] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Der Wantedgrund "Gegen Sie läuft eine Anzeige, im PD melden!" sollte unter "Kleinverbrechen" oder "Sonstiges" hinzugefügt werden, damit Anzeigen im PD bearbeitet werden können.

**Comment by geramy92** [comment]
kann selbst via DB gemacht werden
