### ISSUE TITLE
Tombula verbuggt

### ISSUE THREAD

**Issue by LightningKirito** [TerraTex-Community/TerraTex-Reallife-Reloaded#477]
Tombula ist verbuggt.. Einige Spieler, sowie ich, haben jweils drei Tickets gekauft, jedoch hätte angeblich keiner teilgenommen.

Der Gewinn wird nicht auf einen Gewinner ausgezahlt.

**Comment by Kacper37** [comment]
Kann ich nicht bestätigen! Hat bei mir alles gut geklappt:)

**Comment by geramy92** [comment]
ich glaub dirs zwar, aber es lässt sich scheinbar nicht reproduzieren und tritt nicht mehr auf.... ggf. wurde es versehentlich schon behoben oder ähnl.
