### ISSUE TITLE
Regelwerk @johann

### ISSUE THREAD

**Issue by therealFrankWhite** [TerraTex-Community/TerraTex-Reallife-Reloaded#478]
@Johann0215 
Was für eine Art von Problem ist das?
Rechtschreibdoktor war da :D 

 [x ] Verbesserungsvorschlag

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
konnte keins finden.

Jetzt gehts los
Die mit ** ** markierten Stellen sind gemeint:

§1.2 Das Serverteam behält sich das **Recht** vor, einzelne Personen/Accounts temporär oder permanent von den Plattformen auszuschließen.

§2.1 Aufforderungen des Serverteams sind **Folge** zu leisten

§2.3 Modifikationen, Cheats und Hacks, die einem User Vor- und/oder **Nachteile** verschaffen sind nicht erlaubt.

§2.4 Das Mitwissen, verbreiten und Ausnutzen der in §2.2 und §2.3 stehenden Tatbestände stellt bereits einen **Verstoß** dar.

§1.2.1 Im Falle eines Gamecrash oder ähnlichen hat der User einen **Nachweis** zu erbringen.

Aktionen - Regelwerk

§1.1 Eine Aktion darf nur gestartet werden, wenn mindestens 2 Beamte und 2 **kriminelle Fraktionisten**

§1.5 Bei Aktionen, darf die Fraktion, die **sich** als erstes am Startpunkt aufhält, nicht bei Ihrer Tätigkeit gestört werden.

§1.6 Sollten **sich** Zivilisten oder Neutrale Fraktionen am Aktionsort aufhalten

§1.6 Es dürfen nur Waffen genutzt werden, welche durch das Ausrüsten in der jeweiligen Fraktionsbasis erhalten werden, sowie Schlag-, Hieb-, und Stichwaffen außer **Katana.**

§1.9 Fahndungslevel dürfen erst nach **Beendigung** der jeweiligen Aktion vergeben werden

§1.10 Wird eine Person **lebensgefährlich** verletzt, so darf diese an der Aktion nicht mehr teilnehmen.

§2.3 Bei von Beamten gestarteten **transportbasierten** Aktionen

§2.3.1 Bei von Organisationen (böse Fraktionen) gestarteten **transportbasierten** Aktionen dürfen sich die Beamten

§4.2 Bei einer Geiselnahme dürfen maximal 3 Geiseln in **Gewalt** genommen werden.

Beamte - Regelwerk

§1.1 Das "Beamte - Regelwerk" steht über allen **internen** Regelwerken

§1.2 Nach **Beendigung** des Dienstes sind Beamte

§3.4.1 Die Binds binnen einer Verfolgungsjagt seitens der Beamten müssen einen **Mindestabstand** von 30 Sekunden besitzen.

Kriminelle Organisation - Regelwerk

3.1. Bündnisse sind nur zwischen 2 **bösen** Fraktionen erlaubt.

5.1 Es dürfen nur die Waffen benutzt werden, die aus der Aurüstungskiste dem Spieler vergeben werden sowie Schlag-, Hieb- und Stichwaffen außer **Katana**

5.4. **ein **Ein Angriff 

5.5. **Ein** Ein Angriff auf das Depot muss bei der Verteidiger Fraktion mindestens eine Minute vor Start des **Kampfes** angekündigt werden.

5.5.1. Sobald **ein** ein Angriff auf das Depot angekündigt wurde, dürfen die Verteidiger nicht mehr Offline oder AFK gehen. Sie haben die Pflicht den Angriff **wahrzunehmen**.

5.6. Ein Angriff auf das Depot ist von Sonntag - Donnerstag von 16:30 Uhr bis 21:30 Uhr erlaubt. Von Freitag bis Samstag von 16:30 uhr bis 22:00 Uhr oder nach Absprache mit der **verteidigenden** Fraktion.

6.5. Ein GangFight muss bei der Verteidiger Fraktion mindestens eine Minute vor Start des **Kampfes** angekündigt werden

6.5.1. Sobald ein GangFight angekündigt wurde, dürfen die Verteidiger nicht mehr Offline oder AFK gehen. Sie haben die Pflicht den GangFight **wahrzunehmen**.

6.6. GangFights sind von Sonntag - Donnerstag von 16:30 Uhr bis 21:30 Uhr erlaubt. Von Freitag bis Samstag von 16:30 uhr bis 22:00 Uhr oder nach Absprache mit der **verteidigenden** Fraktion.

7.3.2. Um von der Blacklist entfernt zu werden gibt es zwei Möglichkeiten
a) In einer Blacklist-**Jagd** erschossen zu werden
b) Das Blacklistgeld in **Höhe** von maximal $2.500 zu zahlen.

7.3.3. Wird ein User gesichtet, der sich auf der Blacklist befindet, so ist dieser **zu(kein zu)** mit Blacklist Binds zu binden. Zeigt der User keine **Intentionen**,

**Comment by Johann0215** [comment]
Vielen Dank für das melden der Rechtschreibfehler, ich sollte besser keine Regelwerke mehr schreiben, wenn ich müde bin...

//closed
