### ISSUE TITLE
Neues Wantedsystem - Part I

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#48]
Statt Wanteds erhalten Verbrecher Prozentpunkte. (0-100)

- [x] Verbrechensliste mit Funkcodes erstellen
- [x] Neuer Befehl für Vergabe von Wanteds:  /su [Name] [Verbrechenscode] [Optional: Zusatzbeschreibung]
- [x] Neuer Befehl /sucodes - Öffnet Polizeicomputer direkt in der Codeliste
- [x] Neuer Polizeicomputer: Überarbeitung des jetzigen Computers + statt Wantedanzahl Dropdown mit allen Verbrechen
- [x] Änderung /arrest befehl zu  /arrest Name  => Rest wird automatisch angepasst
- [x] Neuer Befehl: /dearrest [Name] - Min Rang 3 - kann Person aus dem Knast holen (z.B. für Umknasten)
- [x] Änderung Befehl /wanteds zu Liste mit Verbrechern, sortiert nach ihrer Prozente. (Unter 10% wird nicht angezeigt, darüber steht zu den Personen, mit welcher Härte sie gejagt werden dürfen)
- [x] Änderungen /setSDM zu Prozenten (Anstatt 3 Wanted 50%, statt 6 Wanteds 100%)
- [x] Entfernung alte Befehle (/su)
- [x] Überarbeitung Stellbot

**Comment by DarkCitizen** [comment]
Es währe in dem Zusammenhang interessant eine art Akte im PC zu haben, mit einer Liste der einzelnen Verbrechen. Und diese sollte man dann auch einzeln löschen können, um Fehler besser korrigieren zu können.

**Comment by geramy92** [comment]
Der Befehl /checkjailtime wurde entfernt.

Stattdessen gibt der Befehl /jailtime ohne Parameter die eigene Knastzeit aus und mit /jailtime [Username] die Knastzeit eines anderen Users. Nutzbar ist die Commanderweiterung nur für Moderatoren und Beamte

**Comment by geramy92** [comment]
What has to be tested: 
- [ ] /setalka
- [ ] Stellbot

**Comment by geramy92** [comment]
To test additional 

- [ ] /su still working without hidden codes for non admins
