### ISSUE TITLE
LS Medicbase, überarbeiten, BUG

### ISSUE THREAD

**Issue by therealFrankWhite** [TerraTex-Community/TerraTex-Reallife-Reloaded#489]
Was für eine Art von Problem ist das?
Grafikfehler,Bug
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [x ] Verbesserungs- oder Featurevorschlag

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?
keins zu finden
--------------------------------------------------------------------------

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. einfach zur ls medic base fahren
2. in 9 von 10 fällen ist die base unsichtbar bzw einzelne tore

----------------------------------------------------------------------------------
Falls man an eine Umgestaltung denkt , gerne auch nochmal die anzahl an rtws reduzieren, 8Stück werden bestimmt nicht benötigt, 2*NEF wäre vorteilhafter aufgrund der langen Strecken anfangs

**Comment by LightningKirito** [comment]
Ich werde mich der Sache antun.

Die Base ist unsichtbar, weil hierfür etwas in das Script eingetragen werden muss. Darum werde ich mich kümmern. Bei den Fahrzeugen: Erstell mir bitte einmal eine Liste, welche Fahrzeuge du gerne haben und nicht haben möchtest.

**Comment by geramy92** [comment]
https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/blob/master/terratex_reallife/ENGINE/mapFileAdditions/noOcclusionZones_client.lua

**Comment by therealFrankWhite** [comment]
Okey das wäre cool, auf dauer ist das nämlich etwas anstrengend.

Ich denke mit 4 RTW, 2 LSPD (aufgrund der Unterscheidung zwischen LV und LS Base) 
und vlt sogar ein schnelleres Fahrzeug wie einen Bullet, da es den Dienst bei geringer Userzahl auch ohne Helikopter möglich macht.

**Comment by LightningKirito** [comment]
Fahrzeuge wurden erneuert, Sichtbarkeits-Bugs behoben

//closed
