### ISSUE TITLE
Medic Base Bug

### ISSUE THREAD

**Issue by therealFrankWhite** [TerraTex-Community/TerraTex-Reallife-Reloaded#494]
Was für eine Art von Problem ist das?

Fahrzeuge nicht nutzbar und falsche Postion
----------------------------
Setze das x an die richtige Stelle

- [x] Fehler / Bug Meldung
- [ ] Verbesserungs- oder Featurevorschlag
- [ ] Überarbeitung / Entfernung einer Funktion
- [ ] Frage

Gibt es andere Issues oder Pull Request, die etwas mit dem Thema dieses Tickets zu tun haben könnten?

nein
--------------------------------------------------------------------------
- #....

Im Falle eines Featurevorschlages, poste es hier und lösche den Rest des Formulares einfach.

Wie kann ich den Fehler reproduzieren? Welche Schritte muss ich dafür tun?
-----------------------------------------------------------------------
1. Beim versuch in die Fahrzeuge einzusteigen, Nachricht mit Du bist kein Polizist
2. LSPD fahrzeuge stehen in LV, LVPD fahrzeuge stehen in LS

Sende bitte alle nötigen Log-Files / Log-Einträge mit? (Client- und Serverseitig) 
----------------------------------------------------------------------------------
> `log entries client  Pfad: [Your MTA-Installation]/MTA/logs/clientscript.log`   
> `log entries server`

**Comment by LightningKirito** [comment]
Nach Serverneustart behoben/geändert.
