### ISSUE TITLE
/smode - ignore speedlimit greenzone 

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#505]
Wenn ein Teammitglied im Support-Modus ist, sollte das Gewschwindigkeitslimit der greenzone außer Kraft gesetzt werden.

**Comment by geramy92** [comment]
wozu?

**Comment by LightningKirito** [comment]
Bin ich dagegen, Johann. Selbst als Admin im Supportmodus sollte man auf andere Spieler achten.
Das System mit der Greenzone ist nicht ohne Grund so eingestellt.

**Comment by Johann0215** [comment]
Es nervt wenn man da durch düsen will das man gebremst wird :P

**Comment by LightningKirito** [comment]
Und eben das soll auch verhindert werden. Daher sehe ich, und bestimmt auch Geramy, keine Notwendigkeit, dies umzuschreiben. Auch ein Admin im Supportmodus kann sich normal verhalten, wie jeder andere User auch.
