### ISSUE TITLE
Pizzajob Bug

### ISSUE THREAD

**Issue by 48raphael27** [TerraTex-Community/TerraTex-Reallife-Reloaded#51]
WARNING: uffr/ENVIRO/jobs/pizza/pizzaroller.lua:107: Bad argument @ 'destroyElement' [Expected element at argument 1, got boolean]

WARNING: uffr/ENVIRO/jobs/pizza/pizzaroller.lua:108: Bad argument @ 'destroyElement' [Expected element at argument 1, got boolean]

ERROR: uffr/ENVIRO/jobs/pay_skill_sys.lua:142: attempt to perform arithmetic on local 'geldProSkill' (a nil value)

Dieser Fehler tritt auf wenn man beim Pizzajob eine Pizza abgeliefert hat.

**Comment by geramy92** [comment]
Die oberen beiden sind gefixt. 
Was den dritten verursacht muss ich noch herrausfinden.

**Comment by geramy92** [comment]
Ich finde gerade nicht die Ursache. Da die anderen Meldungen bereits gelöst sind, werde ich das lösen sobald er wieder bei uns auf dem Server auftritt und ich das nachvollziehen kann.
