### ISSUE TITLE
GangFight System buggy

### ISSUE THREAD

**Issue by Kacper37** [TerraTex-Community/TerraTex-Reallife-Reloaded#511]
Das Gf System ist teilweise sehr buggy. Es ist schon häufiger vorgekommen, dass Spieler nicht mehr in der Gf welt spawnen und die anderen wiederum schon.
Die Runde wird dann random und iwie sinnlos entschieden und man startet in die nächste runde.

**Comment by Kacper37** [comment]
Ist letztens im Gf zwischen Cf und PP passiert. Kongi Zerstörer Bangerz, TerrorKing, inc-nik und noch jemand, waren dabei am besten bei denen nochmal nachfragen.

**Comment by geramy92** [comment]
wird gelöst mit #520
