### ISSUE TITLE
LVPD - Garage -> Int. "durch die Welt fallen"

### ISSUE THREAD

**Issue by Johann0215** [TerraTex-Community/TerraTex-Reallife-Reloaded#515]
Man fällt durch die Map wenn man aus der LVPD Garage in das Int. geht.

**Comment by LightningKirito** [comment]
Ich schau mir das die nächsten zwei Tage mal an.

**Comment by LightningKirito** [comment]
Bitte nach Serverrestart eine Rückmeldung geben.

**Comment by Johann0215** [comment]
Der Marker in der LVPD Garage wurde erhöht, der Marker binnen  des PD's (nahe Zellen) ist noch immer im Boden.

**Comment by LightningKirito** [comment]
Laut Rückmeldung und Testing behoben. Bei erneutem Fehler neuer Github-Bugreport öffnen.
