### ISSUE TITLE
Häusermarkierungen verlängern

### ISSUE THREAD

**Issue by LightningKirito** [TerraTex-Community/TerraTex-Reallife-Reloaded#523]
Markierungen für Häuser aus der Stadthalle längerer sichtbar machen, 2 Minuten sind zu wenig

**Comment by Johann0215** [comment]
Würde sagen auf 5 Minuten setzen.

**Comment by LightningKirito** [comment]
Die Meinung habe ich eben auch. Weil zwei Minuten reicht nicht aus, von LS nach z.B. LV oder die Dörfer da oben..

**Comment by geramy92** [comment]
Dachte eigentlich das man sich dann einfach selbst ein marker setzt aber
kann man machen

LightningKirito <notifications@github.com> schrieb am Mi., 5. Feb. 2020,
18:34:

**Comment by LightningKirito** [comment]
Geramy, der Vorschlag kam heute von zwei Usern aus der Community.. Habe da auch nichts dagegen, daher hab ich es ins Github geschrieben und schreib es morgen um.

**Comment by LightningKirito** [comment]
Nach Update erledigt.
