### ISSUE TITLE
Hamburger Preise Stimmen nicht

### ISSUE THREAD

**Issue by HammelKen** [TerraTex-Community/TerraTex-Reallife-Reloaded#55]
Hamburger werden beim 24/7 für einen Preis von 1.95$ verkauft. Wenn ich aber einen Hamburger kaufe bezahle ich 4.85$

**Comment by 48raphael27** [comment]
Info: Das ist weil Geramy das Rubbellos weggenommen hat.

**Comment by geramy92** [comment]
sicher das du kein Snack gekauft hast, denn dieser Fehler ist längst gefixt worden und in den Scripts steht es auch korrekt

**Comment by HammelKen** [comment]
Bin mir ziemlich sicher. Habs mehrmals getestet.

**Comment by geramy92** [comment]
Da ich langsam verrückt werde, wird das im Zusammenhang mit #58 gefixxt
