### ISSUE TITLE
Tuning bei Fahrzeugen wird nicht gespeichert

### ISSUE THREAD

**Issue by 48raphael27** [TerraTex-Community/TerraTex-Reallife-Reloaded#56]

**Comment by geramy92** [comment]
eine nähere Beschreibung und Fehlermeldungen wären sinnvoll. Denn bei mir funktioniert es.

**Comment by 48raphael27** [comment]
Wenn ich mein Fahrzeug Tune (Farbe, Reifen oder Spoiler) und ich einen Restart mache ist das Fahrzeug komplett schwarz und alle tuning Teile sind weg

**Comment by geramy92** [comment]
Für den Restart nehme ich mal an hast du auch /gmx genutzt richtig?

**Comment by geramy92** [comment]
Ist nun included in Ticket #57
