### ISSUE TITLE
New Registration UI

### ISSUE THREAD

**Issue by geramy92** [TerraTex-Community/TerraTex-Reallife-Reloaded#59]

**Comment by Grakus98** [comment]
Maybe you can make the window transparent? Like your HUD
It would look better.

**Comment by geramy92** [comment]
Would bei possible if we Change the Color of the Text to white

**Comment by geramy92** [comment]
On the other side all new uis are embetted into a gui with white Background
Am 07.07.2016 19:08 schrieb "Geramy" <gamergeramy@gmail.com>:

> Would bei possible if we Change the Color of the Text to white
>
