### ISSUE TITLE
Evtl Bug im Fraktionsmanagement.

### ISSUE THREAD

**Issue by StalkerGER** [TerraTex-Community/TerraTex-Reallife-Reloaded#62]
Wenn ich über /fmanage Menü einem Mitglied zbsp Rank 5 gebe, wird die Nachricht für alle ersichtlich im Chat geschrieben. 
Danach lädt die Memberliste eine Zeit lang nicht richtig.

Ebenfalls steht da: Du wurdest von Spieler X auf Rang Y gesetzt, egal welche Fraktion dieses macht.

**Comment by geramy92** [comment]
das mit dem Laden kann ich ehrlich gesagt nicht nachstellen die Nachrichten an alle habe ich bereits behoben

**Comment by StalkerGER** [comment]
Viele melden aber, das sie Probleme mit dem /fmanage gelade haben, warum auch immer.
Bei mir ists öfter so, das ich das /fmanage 2 mal benutzen muss, und beim 3ten mal gehts dann.

Bei anderen lädt es nie.

**Comment by geramy92** [comment]
Ich sagte auch nicht das der Fehler nicht auftritt ich sagte ich kann ihn im Script zur zeit nicht nachstellen daher auch das Label => test/**debug**

**Comment by StalkerGER** [comment]
Evtl haste das ja irgendwie schon gefixt, und im nächsten Patch funktionierts dann bei allen.

Ich weiß ja nun auch nicht, ob es irgendwelche Meldungen in der Console gibt, wenn die versuchen aufs /fmanage zuzugreifen.
