### ISSUE TITLE
Gehalt beim Meeresreiniger reduzieren

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#63]
Das Gehalt vom Meeresreiniger sollte drastisch reduziert werden, da er nur AFK genutzt wird. (1/4?)

**Comment by geramy92** [comment]
Gehalt wurde geviertelt und Skillpunkte erhöht
Skill 5 ist zB statt 30k nun bei 500k Meter
