### ISSUE TITLE
Sex im eigenen Haus nicht möglich. HausID 1

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#64]

**Comment by geramy92** [comment]
See #67

**Comment by geramy92** [comment]
kommt die Meldung schon beim /sex oder erst beim /accept sex

**Comment by Maxx4u** [comment]
Kann ich leider nicht mehr beantworten. Das war so extrem viel Sex gestern inGame, dass ich es vergessen habe. Ich werde es heute wieder Testen, damit ich diese Frage beantworten kann.

**Comment by geramy92** [comment]
danke :)
