### ISSUE TITLE
Autos einfach weg über Nacht!

### ISSUE THREAD

**Issue by jurek12** [TerraTex-Community/TerraTex-Reallife-Reloaded#71]
Hallo,

ich habe letztens einen Infernus gekauft beim sportautohaus und habe diesen auch mehrere Tage gehabt bis er dann über Nacht abgeschleppt wurde. Habe ihn dann erst nicht geholt weil ich nur am Jobben war. Vorgestern kaufte ich einem User noch einen Super GT ab und auch dieser wurde von Stalker über Nacht abgeschleppt weil ich ihn falsch geparkt habe was auch völlig legitim ist. Heute wollte ich dann beide Auto holen und bemerke das sie garnicht mehr existieren und aus meiner Fahrzeug Liste einfach gelöscht wurden. Der Infernus und der SuperGT sind einfach weg obwohl sie beide nur abgeschleppt und nicht gelöscht wurden. Habe schon mit Maxx gesprochen, der mich darum bat das ganze nochmal öffentlich zu melden. Habe von mehreren Usern gehört das Ihnen das selbe passiert ist und glaube das es deshalb wichtig ist es hier zu melden. Über eine Lösung würde ich mich freuen, die 610k die mir dadurch verloren gegangen sind schmerzen auf jeden Fall und wie ich eben erwähnte fehlen auch bei anderen Usern Autos auf einmal!

Schönen Abend noch!

MFG jurek aka Lukas

**Comment by StalkerGER** [comment]
Was mich an der Sache am meisten interessiert, ob das nur passiert wenn ich die Leute abschleppe, oder auch wenn andere PDler das tun.

Spontan würde mir evtl ein Bug per Adminabschleppung einfallen, wenn ich das per Click-System mache.

Vielleicht finden sich ja noch ein Paar andere User, die uns mitteilen könnten, welches Fahrzeug von wem abgeschleppt wurde und verschwunden ist.

**Comment by geramy92** [comment]
Admin und PD ist normalerweise die selbe Funktion... wäre echt mega strange wenn das der Fall wäre

**Comment by jurek12** [comment]
Ceeser Hiro sind auch betroffen und bei mir ist es infernus und super gt
Am 13.07.2016 09:58 schrieb "Geramy" <notifications@github.com>:

Admin und PD ist normalerweise die selbe Funktion... wäre echt mega strange
wenn das der Fall wäre

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/issues/71#issuecomment-232283990>,
or mute the thread
<https://github.com/notifications/unsubscribe/ATdlXhViJNZdQ66FN95QgogKoxygTMj-ks5qVJqrgaJpZM4JJzU4>
.

**Comment by Kacper410** [comment]
Jo ist mir auch passiert Remington full tuned weg :(

**Comment by geramy92** [comment]
wann war das?

**Comment by jurek12** [comment]
Bei kacper auch heute Nacht dad passiert anscheinend beim Restart

Am 14.07.2016 14:57 schrieb "Geramy" <notifications@github.com>:

**Comment by StalkerGER** [comment]
Dann bleibt nur die Frage, passiert das nur bei abgeschleppten Fahrzeugen, oder auch bei normal geparkten?
Falls durchn GMX der kauf irgendwie Rückgängig gemacht wird, warum wird dann das Geld nicht Rückerstattet?
Falls ersteres nicht passiert, warum passierts dann nur bei abgeschleppten Fahrzeugen?

Unterschied zwischen Admin und PD abschleppen kann ich jetzt mit gewissheit ebenfalls verneinen, ich war gestern Abend gar nicht online zum abschleppen.

**Comment by jurek12** [comment]
Passiert nur bei abgeschleppten Autos und nicht bei normal geparkten

Am 14.07.2016 16:07 schrieb "StalkerGER" <notifications@github.com>:

**Comment by geramy92** [comment]
[13.7.2016 - 21:39:54] [TTeam]DarkCitizen: Fahrzeugslot 1 | Besitzer Kaiyuzo | Abschlepper [TTeam]DarkCitizen 
 [14.7.2016 - 14:10:9] Kenny: Fahrzeugslot 1 | Besitzer Kacper | Abschlepper Kenny 
 [14.7.2016 - 14:25:19] iHostiiX: Fahrzeugslot 1 | Besitzer Zerstoerer10 | Abschlepper iHostiiX

**Comment by jurek12** [comment]
Der meinte zu mir heute Nacht

Am 14.07.2016 17:20 schrieb "Geramy" <notifications@github.com>:

**Comment by geramy92** [comment]
Frag ihn bitte mal ob das sein Fahrzeug in Slot 1 war oder ob das entsprechende Fahrzeug gar nicht in den Logs steht (vorheriger Post)

**Comment by jurek12** [comment]
Bei meinem infernus waren es Slot 2 und 3 beide weg bekommt man da
eigentlich was erstattet

Am 14.07.2016 17:22 schrieb "Geramy" <notifications@github.com>:

**Comment by geramy92** [comment]
damit warst nicht du gemeint sondern Kacper
