### ISSUE TITLE
2 "Waffeninventare"

### ISSUE THREAD

**Issue by 48raphael27** [TerraTex-Community/TerraTex-Reallife-Reloaded#72]
Wäre es möglich, dass ein Spieler 2 Waffeninventare hat? Also eins für Dienstwaffen und eins für Private Waffen, weil wenn ein Cop /rearm macht sind alle seine Waffen weg die er selbst gekauft hat.

**Comment by geramy92** [comment]
dazu müsste das gesamte Waffensystem umgeschrieben werden, da dieses mit dem nativen von GTA-SA arbeitet.

Ggf. wäre es zukünftig eine Option ein eigenes Waffensystem mit Slots zu schreiben und diese entsprechend anzupassen. Vorraussetzung wäre denke ich dennoch das neue Inventarsystem (siehe #44)

**Comment by DarkCitizen** [comment]
Ein eigenes Waffeninventar würde dann auch ein Spray für das PD ermöglichen. Der Slot wird ja schon durch den Schlagstock belegt

**Comment by geramy92** [comment]
Der schlagstock und das Spray sind NICHT im selben slot. 
Defakto ist es nur unsinnig den cops ein Spray zu geben, wenn sie ein Tazer haben. Zumal das sicher zu noch mehr missbrauch führen würde

**Comment by FFrozen** [comment]
ein Tazer wird nur in extrem bedingungen genutzt, während ein Pfefferspray auch oft von Zivilisten oder ein Polizist genutzt wird, wenn man sich bedroht fühlt

**Comment by geramy92** [comment]
ändert an meiner aussage nichts

**Comment by geramy92** [comment]
Ich schließe das Ticket, da es in der Zukunft in Rahmen des neuen Inventarsystems in ähnlicher Art und Weise umgesetzt wird.
