### ISSUE TITLE
Prestige Upgrade Info / Upgraden ohne Marker

### ISSUE THREAD

**Issue by Maxx4u** [TerraTex-Community/TerraTex-Reallife-Reloaded#8]
Es wäre schön wenn man die Prestige Upgrade Info bzw. das Upgraden selbst ohne dem Prestige Marker durchführen kann.
Auch sollte es möglich sein, das man beim Upgrade info folgendes erfährt:
-Bonus aktuell
-Upgrade Preis und Bonus nach dem Update.

**Comment by geramy92** [comment]
Grundsätzlich hätte ich nichts dagegen.
Wäre aber auch sinnvoller in der Bankingapp (siehe Biz) aufgehoben. Wäre ein zusätzliche Option um den TLT mehr zu benutzen....

**Comment by Maxx4u** [comment]
ja, ne "Immobilien" bzw. "Immobilien-Verwaltungs" app währe wohl angebrachter.
Wäre ich dafür.

**Comment by geramy92** [comment]
See new Ticket #23
