### ISSUE TITLE
Fischerjob bug

### ISSUE THREAD

**Issue by 48raphael27** [TerraTex-Community/TerraTex-Reallife-Reloaded#83]
Wenn ich im Fischerboot stehe und ein andere das Boot fährt und ich einen Fisch fange, dann zählt der Fischcounter nur eins hoch obwohl ich 2 Fische fange. (ich kann aber auch nur 80 statt 160 Fische fangen)

**Comment by geramy92** [comment]
das ist richtig so, da die anzeige keine 2 fische unterstützen würde
