### ISSUE TITLE
Frakkassen Log /fmanage

### ISSUE THREAD

**Issue by DarkCitizen** [TerraTex-Community/TerraTex-Reallife-Reloaded#84]
Es währe gut, wenn unter /fmanage das Log der der Frakkasse einzusehen währe, wie es früher im CP war.

**Comment by geramy92** [comment]
Da mir persönlich zu Performencelastig, wäre das eine Sache für die zukünftige API / UCP -> https://github.com/TerraTex-Community/TerraTex-Reloaded-Reallife-Node-API
