### ISSUE TITLE
Vorschlag: Eigener Abgebapunkt für Helis am Flugjob

### ISSUE THREAD

**Issue by Ceeserxx** [TerraTex-Community/TerraTex-Reallife-Reloaded#93]
Es wäre schön, wenn zwischen dem normalen abgabe Marker und dem Zaun, da dort noch viel freier Platz ist hinter der Landebahn, ein Helipad wäre mit extra abgabe Marker wäre, denn dann können sich Helis und Flugzeuge nichtmehr in die Quere kommen und man läuft keine Gefahr jemanden zu blockieren/rammen/gefährden und mann müsste als Heli nichtmehr warten. Für das Helipad wäre die Anflugsrichtung auch egal, da mein keine Landebahn mehr kreuzt. Außerdem lernen dann Zwangsläufig auch leute mit Flugzeugen vorsichtiger zu landen und nicht über den Abgabe marker zu schießen.

**Comment by geramy92** [comment]
Ehrlich gesagt kann ich dir ganze Argumentation nicht nachvollziehen.
Alles was für mich Sinn ergibt ist lediglich:

> mann müsste als Heli nichtmehr warten.

**Comment by scriptcodeDE** [comment]
Related to #143
