### ISSUE TITLE
Spray

### ISSUE THREAD

**Issue by DarkCitizen** [TerraTex-Community/TerraTex-Reallife-Reloaded#95]
Das Spray wirk auf alle Spieler in der Umgebung, auch wenn diese weiter entfernt stehen. Vorraussetzung ist lediglich, das irgendjemand getroffen wird. Dann wirkt es aber auch auf den Nutzer.

**Comment by geramy92** [comment]
Wie bereits erwähnt im Teamspeak, ghreifen wir auf das Event https://wiki.multitheftauto.com/wiki/OnClientPlayerChoke zu sollte es also daher einen Fehler geben, so ist das ein Bug von MTA, den ich so ohne weiteres nicht beheben kann.

**Comment by geramy92** [comment]
Der Bug an sich ist zwar nicht behebbar (da MTA:SA Bug) aber eine Einschränkung der Entfernung, würde das Problem einschränken.
