### ISSUE TITLE
MTA: TT Bug

### ISSUE THREAD

**Issue by Nightmarefoxy** [TerraTex-Community/TerraTex-Reallife-Reloaded#98]
Hatte in MTA mit meinem ehepartner noch nie sex aber mir wird an gezeigt das "mein kind olivia auf eigenen beinen steht" 
![mta-screen_2016-07-23_00-55-00](https://cloud.githubusercontent.com/assets/20605232/17073586/62843598-5072-11e6-8110-c6d994f036d0.png)

**Comment by geramy92** [comment]
ist bereits mit https://github.com/TerraTex-Community/TerraTex-Reallife-Reloaded/commit/78a92f87ba19a925e78fc87d7918590703d80b92 behoben
